#!/usr/bin/env bash
set -euo pipefail

echo "What should the file name be?"
printf ">> "
read filename

echo "What cmd should the test run?"
printf ">> "
read testcmd

echo "What should the test name be?"
printf ">> "
read testname

s touch "~/.local/share/chezmoi/private_dot_config/exact_goss/$testname.yml"

jq --null-input "
{
'$testname': { exit-status: 0, timeout: 10000, exec: '$testcmd' }
}
" | tee "~/.local/share/chezmoi/private_dot_config/exact_goss/$filename.yml"
