#!/usr/bin/env bash
set -o pipefail

errs=$(s goss run-in-order ~/.config/goss)
o=$?

if [[ $o -ne 0 ]]; then
    # TODO check if any of the errors have an autofix
    # if none do then exit non 0
    set -e
    echo "Something borked, trying to fix and then rerunning goss fixer (unless fixing fails)"
    s goss autofix-input <<<"$errs"
    s goss fix-all-in-order
fi
