#!/usr/bin/env bash
set -euo pipefail

orig_dir=$PWD

cd $(mktemp -d)
workingdir="$PWD"

echo "Create gossfile and exit when done"

$SHELL

echo "What should the file name be?"
printf ">> "
read testname

tgt_path="$HOME/.config/goss/$testname.yml"
mv goss.yaml "$tgt_path"

chezmoi add "$tgt_path"
chezmoi git add "private_dot_config/exact_goss"
chezmoi git commit -- -m "autocommit goss test"

cd "$orig_dir"
