#!/usr/bin/env bash
set -euo pipefail

TARGET_DIR=${1:w"Required arg"}

fd -t d --max-depth=1 . $TARGET_DIR | sort | xargs -I_ bash -c "s goss run-in-order $TARGET_DIR/_"
fd -t f -t l --max-depth=1 . $TARGET_DIR | sort | xargs -I_ bash -c "echo 'running _'; chronic goss -g $TARGET_DIR/_ validate || exit 255"
