#!/usr/bin/env bash

if command -v sysctl >/dev/null 2>&1; then
    timeout 8 bash -c "sudo sysctl -w net.ipv4.ip_forward=1"
fi

s cbi start-vpn

bw sync

alacritty --config-file $HOME/.config/alacritty/work.yml
