#!/usr/bin/env bash
set -euo pipefail

if command -v sysctl >/dev/null 2>&1; then
    sudo sysctl -w net.ipv4.ip_forward=1
fi

if ! s cbi test-vpn-is-active; then
    zenity --warning --text "CBI VPN not active, shit prolly wont work"
fi

bw sync

if ! s cbi docker login; then
    zenity --warning --text "CBI docker login failed"
fi

alacritty --config-file $HOME/.config/alacritty/work.yml
