#! /usr/bin/env bash
set -euo pipefail

job_name=${1:-$(s cbi svc-select-dwim)}

s cbi nomad job inspect "$job_name" | jq ".Job.TaskGroups[0].Tasks[] | select(.Name==\"$job_name\") | .Services[0].Tags[] | select(startswith(\"build-\"))" -r | cut -d- -f2
