#!/usr/bin/env bash
set -euo pipefail

export FZF_DEFAULT_OPTS='--height 90% --reverse --border'
image=$(docker images --format '{{.Repository}}:{{.Tag}}' | fzf-tmux --reverse --multi)
if [[ $image != '' ]]; then
  echo -e "\n  \033[1mDocker image:\033[0m" $image
  read -e -p $'  \e[1mOptions: \e[0m' -i "-it --rm" options

  printf "  \033[1mChoose the command: \033[0m"
  cmd=$(echo -e "/bin/bash\nsh" | fzf-tmux --reverse --multi)
  if [[ $cmd == '' ]]; then
    read -e -p $'  \e[1mCustom command: \e[0m' cmd
  fi
  echo -e "  \033[1mCommand: \033[0m" $cmd

  export FZF_DEFAULT_COMMAND=""
  export FZF_DEFAULT_OPTS=""

  history -s runc
  history -s docker run $options $image $cmd
  echo ''
  docker run $options $image $cmd
fi
