#!/usr/bin/env bash
set -euo pipefail

# TODO should accept '-' as a param indicating read stdin (rather than assume you remember stdin)

if [[ -n ${1:-""} ]] && [[ -s "$1" ]]; then
    cat "$1" | rg ^service | choose 1
else
    timeout 1 rg ^service | choose 1
fi
