#!/usr/bin/env bash
set -euo pipefail

proto_path=${1:-"$(s cbi svc name-to-proto-path "$(s cbi svc select-dwim)")"}
proto_path=$(realpath "$proto_path")

# TODO should I run proto reload in the target repo?
svc_name=$(cat "$proto_path" | s cbi proto get-svc-name-from-file)
pkg_name=$(cat "$proto_path" | s cbi proto get-pkg-name-from-file)
import_path=$(s cbi proto walkup-for-import-path "$proto_path")

grpcurl -import-path "$import_path" -proto "$import_path/cbinsights/$pkg_name/$pkg_name.proto" list "$pkg_name.$svc_name"
