#!/usr/bin/env bash
set -euo pipefail

REGION=${REGION:=us-east-1}

docker login -u AWS -p "$(aws ecr get-login-password --region "$REGION")" "https://$(aws sts get-caller-identity --query 'Account' --output text).dkr.ecr.${REGION}.amazonaws.com"
