#!/usr/bin/env bash
set -euo pipefail

rclone_flags=$(cat ~/.config/rclone/rclone.conf | awk -F ' *= *' '{ if ($1 ~ /^\[/) section=$1; else if ($1 !~ /^$/) print $1 section "=" "\"" $2 "\"" }' | rg '\[orgbox\]' | sd -- '(.+)\[\w+\]="(.*)"' '-o $1=$2' | tr '\n' ' ')
docker volume create org-dropbox -d rclone $rclone_flags
