#!/usr/bin/env bash
set -euo pipefail

activeticket=$(s jira select-ticket "${1:-""}" | jq -r '.key | select(. != null)' | xargs)

s jira set-current-ticket "$activeticket"
jira move-to-in-progress "$activeticket"

echo $activeticket
