#!/usr/bin/env bash
set -euo pipefail

# todo add filter for key arg
jira available-tickets | jq '.issues | map({key: .key, description: .fields.summary, reporter: .fields.reporter.displayName })' | s fzf select-by-json-key "key" "description" | jq -r '.key | select(. != null)' | xargs >"$JIRA_ACTIVE_TICKET_FILE"
jira move-to-in-progress "$(cat "$JIRA_ACTIVE_TICKET_FILE")"
