#!/usr/bin/env bash
set -euo pipefail

cmd=""
script_name=""

while test $# -gt 0; do
    case "$1" in
        --)
            shift
            cmd="$*"
            break
            ;;
        *) script_name="$script_name$1 "
            ;;
    esac
    shift
done
script_name="$(echo "$script_name")"
script_path="$(s which $script_name)"

dest_dir=$(dirname "$script_path")
scriptgit() {
    git -C "$dest_dir" $*
}
scriptgit stash --all

mkdir -p "$(dirname "$script_path")"
cat > "$script_path" <<EOF
#!/usr/bin/env bash
set -euo pipefail

EOF


chmod +x "$script_path"
if [[ -z "$cmd" ]]; then
    s edit "$script_name"
else
    echo "$cmd" >> "$script_path"
    echo >> "$script_path"
fi


s mkhelp "$script_name"


scriptgit add chez-ignore/scripts
scriptgit -- commit --message 'added new s script'

scriptgit stash pop
