#!/usr/bin/env bash
set -euo pipefail

ssh "${1}" '
bwpassword="'"$(secret-tool lookup password bitwarden-primary)"'"
if [ -n $BW_SESSION ] && bw unlock --check >/dev/null 2>&1; then
	return
fi
if ! bw login --check >/dev/null 2>&1; then
	BW_SESSION=$(bw login --raw $bwpassword)
fi
if ! bw unlock --check >/dev/null 2>&1; then
	BW_SESSION=$(bw unlock --raw $bwpassword)
fi
if ! bw unlock --check >/dev/null; then
	echo "unlock failed somehow"
	return 1
fi
echo export BW_SESSION="$BW_SESSION" > .bw-auth

'

