#!/usr/bin/env bash
set -euo pipefail

echo "Broken need to migrate to the new api but below doesnt work yet"
msnow=$(($(date +%s%N) / 1000000))
http --follow --body "https://backend-unified.mylirr.org/plan" from==1BH to==_GC fares==ALL time==$msnow
