#!/usr/bin/env bash
set -euo pipefail

ssh "$1" "$(s cat ssh generate-keypair)"
SSH_KEY_TO_ADD="$(ssh "$1" "cat ~/.ssh/id_ed25519.pub")" SSH_KEY_TITLE="autogen-${2:-"$1"}-s-script-key" s gitlab ssh-key-add
