#!/usr/bin/env bash
set -euo pipefail

vpshost="$1"
vpsname="${2:-$1}"

export UNTIL_CMD_VERBOSE=1
export FOR_REMOTE_SETUP=1

ssh-copy-id $vpshost

ssh -t $vpshost "
sudo mkdir -p /root/.ssh
sudo cp /home/jmccown/.ssh/authorized_keys /root/.ssh/authorized_keys
sudo chmod 600 /root/.ssh/authorized_keys
sudo chown root:root /root/.ssh/authorized_keys
"

chronic ssh "root@$vpshost" "hostname $vpsname"

_reboot() {
  echo "starting reboot"
  ssh "root@$vpshost" reboot || true
  s util until-cmd-passes ssh "$vpshost" echo hi
  s util until-cmd-passes s bitwarden remote-auth "$vpshost"
  echo "Rebooted and bw login"
}

gum spin --spinner meter --title "Tailscale setup" -- s tailscale remote-setup "root@$vpshost"

ssh -t "$vpshost" "$(cat ~/.local/share/chezmoi/.chezmoiscripts/run_linux--sshd-config.sh.tmpl | CHEZ_FULL=1 chezmoi execute-template)"

gum spin --spinner hamburger --title "Apt full-upgrade" -- s util until-cmd-passes ssh $vpshost "apt-get full-upgrade -y"
echo "Initial apt install done at $SECONDS"

ssh $vpshost "ssh-keygen -q -t ed25519 -b 4096 -N '' -f ~/.ssh/id_ed25519 -C ${SSH_EMAIL:-"jackmac79@gmail.com"}"

export SSH_KEY_TO_ADD="$(ssh "$vpshost" "cat ~/.ssh/id_ed25519.pub")"
export SSH_KEY_TITLE="autogen-$vpshost-key"
tee -a ~/.ssh/authorized_keys <<<"$SSH_KEY_TO_ADD"
chezmoi add ~/.ssh/authorized_keys
s gitlab ssh-key-add

chronic ssh "root@$vpsname" '
sudo apt install -y snapd
if ! command -v bw ; then sudo snap install bw; fi
'

s misc setup-chez-remote $vpshost

if [[ -z "${MKDROPLET_SKIP_SWARM:-""}" ]]; then
  s docker swarm add-remote-server-as-worker "$(doctl compute droplet list --format PublicIPv4,Name | grep "$vpsname" | choose 0)" "root@$vpsname"
fi

ssh "$vpsname" "direnv exec ~ s goss autofix"
s misc minions-do-async 'chezmoi git pull && chezmoi apply .config/goss && chezmoi apply .ssh'
