#!/usr/bin/env bash
set -euo pipefail

cd ~/Projects/gitlab.com/

s gitlab list-all-projects |
    jq 'select(.path_with_namespace | startswith("jackmac92")) | "git clone \(.ssh_url_to_repo) \(.path_with_namespace)"' |
    xargs -n 1 bash -c
