#!/usr/bin/env bash
set -euo pipefail

s gitlab list-all-projects |
    jq 'select(.web_url | contains("cbinsights")) | "git clone \(.ssh_url_to_repo) \(.path_with_namespace)"' |
    xargs -n 1 bash -c

# echo $LAB_CORE_HOST | s util strip-protocol
