#!/usr/bin/env bash
set -euo pipefail

cd ~/cbinsights/gitlab.cbinsights.com

s gitlab list-all-projects |
    jq 'select(.web_url | contains("cbinsights")) | "if [ ! -d \(.path_with_namespace) ]; git clone \(.ssh_url_to_repo) \(.path_with_namespace) ; fi"' |
    xargs --no-run-if-empty -n 1 bash -c
