#!/usr/bin/env bash
set -euo pipefail

IP=127.0.0.1
first_port=2000
last_port=65000

for ((port = $first_port; port <= $last_port; port++)); do
    if (echo >/dev/tcp/$IP/$port) >/dev/null 2>&1; then
        echo $port
        break
    fi
done
