#!/usr/bin/env bash
set -euo pipefail

cd ~/.config/nixpkgs
nix flake update
chezmoi add flake.lock
trap "git -C ~/.local/share/chezmoi/ checkout -- private_dot_config/exact_nixpkgs/flake.lock; exit 1" ERR
s util niv-try-upgrade
