#!/usr/bin/env bash
set -euo pipefail

cd $(mktemp -d)

deno eval --unstable '
import puppeteer from "https://deno.land/x/puppeteer@9.0.2/mod.ts";

const browser = await puppeteer.launch();
const page = await browser.newPage();
const fullPath = Deno.args[0]
await page.goto(`file://${fullPath}`);
await page.pdf({ path: "./puppet.pdf" })
await browser.close()
' $1

realpath ./puppet.pdf
