#!/usr/bin/env bash
set -euo pipefail

python -c '
from collections import OrderedDict
import json
import sys

def _sort_json_types(val):
    t = type(val)
    return {str: 1, int: 1, bool: 1, dict: 30, list: 20}[t]

def sort_keys_by_type(obj):
    k = obj.keys()
    result = OrderedDict()
    for z in sorted(k, key=_sort_json_types):
        if type(obj[z]) == dict:
            result[z] = sort_keys_by_type(obj[z])
        else:
            result[z] = obj[z]
    return result
result = sort_keys_by_type(json.load(sys.stdin))
out = json.dumps(result)
print(out)
'
