#!/usr/bin/env bash
set -euo pipefail

choice=$(ls ~/.local/app-image | fzf)

cd $(mktemp -d)

$choice --appimage-extract

dtopfile=$(ls squashfs-root/*.desktop)

cat $dtopfile | sed '/^Exec/c\Exec=$HOME/.local/app-image/'"$choice" >"~/.local/share/applications/$choice.desktop"

rm -rf squashfs-root
