#!/usr/bin/env bash
set -euo pipefail

APPIMAGEDIR="$HOME/.local/app-images"

choice=$(ls $APPIMAGEDIR | fzf)

cd $(mktemp -d)

chronic $choice --appimage-extract

dtopfile=$(ls squashfs-root/*.desktop | fzf)

cat $dtopfile | sed '/^Exec/c\Exec='"$APPIMAGEDIR/$choice" | sponge "~/.local/share/applications/$choice.desktop"

rm -rf squashfs-root
