#!/usr/bin/env bash
set -euo pipefail

url="$1"
filename="$((yt-dlp --get-filename "$url" || youtube-dl --get-filename "$url") | sed 's/#[^ ]*//g')"
url="$((yt-dlp --format "mp4" --get-url "$url" || youtube-dl --get-url "$url") | head -n 1)"
# url="$(s util http-follow-redirects "$url")"
s util motrix-send-aria2.addUri "$url" "$filename"
