#!/usr/bin/env bash
set -euo pipefail

cd ~/.local/share/chezmoi/private_dot_config/exact_nixpkgs

niv update

trap "git checkout -- nix/sources.json; exit 1" ERR
chezmoi apply -i files ~/.config/nixpkgs
chezmoi apply ~/.config/nixpkgs
git add nix
git commit -m "niv update" && git push
