#!/usr/bin/env bash
set -euo pipefail

inputfile=${1:-$(fd -e mp4 -e avi -e mkv -e webm -e mov | fzf | xargs realpath)}
inputextension=$(echo "$inputfile" | sd '.*\.(.*)' '$1')
outputextension=${2:-"$inputextension"}
inputFileBaseName=$(basename "$inputfile" ".$inputextension")
outputFileDir=$(dirname "$inputfile")
outputFileBasename=$(yad --entry --text="Video file name" || "$inputFileBaseName")

losslesscut "$inputfile"
final_cut=$(fd -e mkv "$inputFileBaseName" "$(dirname "$inputFile")" | rg -v "$inputfile" | fzf)
outputfile="$outputFileDir/Optimized-$outputFileBasename.$outputextension"

extraFlags=""

if [[ "$outputextension" = "mp4" ]]; then
    extraFlags="-c:a aac"
fi

set -x

# 265 is an improvement on stock codec
# higher crf values lower bitrate (smaller video, maybe lower quality), don't go higher than 30
ffmpeg -i "$inputfile" -sn -map 0 -map -0:s -c copy -vcodec libx265 -crf 20 $extraFlags "$outputfile" </dev/null
# | yad --auto-kill --enable-log=details --log-expanded --progress --pulsate --text "Optimizing video"

echo "$outputfile"
