#!/usr/bin/env bash
set -euo pipefail

pathParts=$(echo "$PATH" | tr : \\n)
toRemove=$(echo "$pathParts" | fzf --multi --header "Select components to remove from PATH")

newPathParts=$(s util lista-minus-listb <(echo "$pathParts") <(echo "$toRemove"))

PATH=$(echo "$newPathParts" | tr $'\n' ':' | sd ':$' '')

export PATH
