#!/usr/bin/env bash
set -euo pipefail

if ! (emacsclient --eval "(server-running-p)"); then
  echo "Emacs server is not running."
  exit 1
fi

direnv exec ~/.local/fullenv emacsclient -e '(jm/spotlight-popup)'
