#!/usr/bin/env bash
set -euo pipefail

vpsname="$1"

TAILAUTH=$(bw get item tailscale | jq '.fields[] | select(.name == "api-key").value' -r)
device_id=$(https --auth "$TAILAUTH:" "api.tailscale.com/api/v2/tailnet/jackmac79@gmail.com/devices" | jq --arg tgt "$vpsname" '.devices[] | select(.hostname == $tgt) | .id' -r)

if [[ -n "$device_id" ]]; then
    https --body --auth "$TAILAUTH:" DELETE "api.tailscale.com/api/v2/device/$device_id"
fi
