#! /usr/bin/env bash
set -euo pipefail

hostname=$1
port=$2

echo | openssl s_client -servername $hostname -connect $hostname:$port 2>/dev/null | openssl x509 | sudo tee /usr/local/share/ca-certificates/sscript-$hostname.crt
sudo update-ca-certificates
