#!/usr/bin/env bash
set -euo pipefail

inputfile=${1:-$(fd -e mp4 -e avi -e mkv -e webm -e mov | fzf | xargs realpath)}

set -x
ffmpeg -i "$inputfile" -c copy -an "$inputfile.noaudio"
mv -f "$inputfile.noaudio" "$inputfile"
