#!/usr/bin/env bash





#!/bin/bash

PACKAGE_NAME="$1"

if [ -z "$PACKAGE_NAME" ]; then
  echo "Usage: $0 <package-name> [version]"
  exit 1
fi

if [ -z "$2" ]; then
  VERSION=$(curl -s "https://pypi.org/pypi/$PACKAGE_NAME/json" | jq -r '.info.version')
else
  VERSION="$2"
fi


URL="https://pypi.io/packages/source/${PACKAGE_NAME:0:1}/$PACKAGE_NAME/$PACKAGE_NAME-$VERSION.tar.gz"
SHA256=$(nix-prefetch-url "$URL" 2>/dev/null)

cat <<EOL
{ lib, buildPythonPackage, fetchPypi }:

buildPythonPackage rec {
  pname = "$PACKAGE_NAME";
  version = "$VERSION";

  src = fetchPypi {
    inherit pname version;
    sha256 = "$SHA256";
  };

  meta = with lib; {
    description = "A Python package from PyPI"; # Add a proper description
    license = licenses.mit; # Replace with the correct license
  };
}
EOL


