#!/usr/bin/env bash
set -euo pipefail

repo_to_clone=${1:-$(xclip -selection clipboard -o)}
repo_to_clone=$(s git convert-ssh-url-to-http "$repo_to_clone")

cd $GIT_CLONES_DIR
git clone $repo_to_clone $(s git convert-http-remote-to-clone-path <<<"$repo_to_clone")
