#!/usr/bin/env bash
set -euo pipefail

git log --pretty='format:%C(yellow)%h %G? %ad%Cred%d %Creset%s%C(cyan) [%cn]' --decorate --after="$(date --rfc-3339=date -d "$1") 0:00" --before="$(date --rfc-3339=date -d "$1") 23:59" -- ${*-}
