#!/usr/bin/env bash
set -euo pipefail

repo=${1:-$PWD}
repo=$(realpath $repo)

echo "Add repo to zoxide"
zoxide add $PWD
echo "Add repo to emacs"
timeout 5 emacsclient --no-wait --eval "$(printf "(jm/register-project \"%s\")" "$repo")"
