#!/usr/bin/env bash
set -euo pipefail

remote=${1:-$(git remote get-url origin)}
basepath="$HOME/repos/gitlab.com"
echo "$basepath/$(s git remote-to-http-url "$remote" | sd '.com/' '\t' | cut -f2 -d $'\t')"
