#!/usr/bin/env bash
set -euo pipefail

gitmote=$(git remote get-url origin)

if [[ $gitmote = git@* ]]; then
  gitmote=$(s git convert-ssh-url-to-http "$gitmote")
fi

httpUrl=$(bash -c '[[ '"$gitmote"' =~ (.*)?.git ]] && echo "${BASH_REMATCH[1]}"')

echo "$httpUrl"
