#!/usr/bin/env bash
set -euo pipefail

target_svc=${1:-"$(s cbi svc select-dwim)"}
echo "$CBI_DEV_DIRECTORY/$target_svc/.__proto_dont_modify__/cbinsights/$(echo "$target_svc" | tr -d '-')/$(echo "$target_svc" | tr -d '-').proto"
