#!/usr/bin/env bash
set -euo pipefail

target_svc=${1:-"$(s cbi svc select-dwim)"}
target_svc=$(choose --field-separator="/" -1 <<<"$target_svc")
smushedname="$(echo "$target_svc" | tr -d '-')"
repodir="$(s cbi svc name-to-directory "$target_svc")"

protoindunder="$repodir/.__proto_dont_modify__/cbinsights/$smushedname/$smushedname.proto"
protoinrepo="$repodir/proto/$smushedname.proto"

if [ -f "$protoindunder" ]; then
    echo "$protoindunder"
elif [ -f "$protoinrepo" ]; then
    echo "$protoinrepo"
else
    echo "No proto found for service!"
    exit 1
fi
