#!/usr/bin/env bash
set -euo pipefail

# TODO provide random port for go server to listen on
go mod vendor
consul services register -http-addr=http://localhost:8500 -name $SVC_NAME -address $(hostname -I | choose 0) -port 50051
trap "consul services deregister -id=$SVC_NAME" EXIT SIGINT
go run ./main.go
