#!/usr/bin/env bash
set -euo pipefail

case $PWD/ in
    $HOME/cbinsights/*) realpath --relative-base $HOME/cbinsights/gitlab.cbinsights.com/ $(git root-directory) ;;
    *) s cbi svc select --sync ;;
esac
