#!/usr/bin/env bash
set -euo pipefail

tgt="${1:-$EMACS_SOCKET_NAME}"

cd "$HOME/.local/share/emacs.profiles/$tgt"

while true; do
  if doom sync; then
    break
  fi
  sleep 2
done

emacs --bg-daemon

until emacsclient -s "$tgt" --eval '(server-running-p)'; do
  sleep .5
  printf "server not running yet."
done

emacsclient -s "$tgt" '(server-stop)'
