#!/usr/bin/env bash
set -euo pipefail

cd ~/.doom.d
# suggested command, but I get no func found for buttercup

# emacs -batch -f package-initialize -L . -f buttercup-run-discover
emacs -f buttercup-run-discover
