#!/usr/bin/env bash
set -euo pipefail

# TODO test config differences, by cloning the emacs profile with zfs and changing

SINGLE_TEST_TIMEOUT_SECS=60

fd --type file -e spec.el --max-depth=1 . $DOOMDIR/emacs-config-tests.d |
    xargs -P1 -I_ bash -c "echo 'Running _';timeout $SINGLE_TEST_TIMEOUT_SECS emacs -l ~/.local/share/emacs/director-test-bootstrap.el -l $DOOMDIR/emacs-config-tests.d/init.el -l _ || exit 255"
