#!/usr/bin/env bash
set -euo pipefail

fd --type file -e spec.el --max-depth=1 . ~/.doom.d/emacs-config-tests.d |
    xargs -P1 -I_ bash -c "echo 'Running _'; emacs -l ~/.local/share/emacs/director-test-bootstrap.el -l ~/.doom.d/emacs-config-tests.d/init.el -l _ || exit 255"
