#!/usr/bin/env bash
set -euo pipefail

# {
#   "ID": "d8639178-7ca6-4710-b022-bf83e7fd0282",
#   "Version": 26,
#   "Message": "",
#   "Success": true,
#   "BlobURLGet": "",
#   "BlobURLGetExpires": "0001-01-01T00:00:00Z",
#   "ModifiedClient": "2021-10-26T17:43:57.595595Z",
#   "Type": "DocumentType",
#   "VissibleName": "Quick sheets",
#   "CurrentPage": 0,
#   "Bookmarked": false,
#   "Parent": ""
# }

# cat "$REMARKABLE_QUICK_SHEET_CACHE_DIR/last-check"

last_check_ts=$(cat "$REMARKABLE_QUICK_SHEET_CACHE_DIR/last-check")
last_check_page=$(cat "$REMARKABLE_QUICK_SHEET_CACHE_DIR/last-page")

curr_info=$(rmapi -ni stat "Quick sheets")
curr_page=$(jq -r ".CurrentPage"<<<"$curr_info")

rmapi -ni geta "Quick sheets"
qpdf --empty --pages "Quick sheets-annotations.pdf" ((last_check_page+1))-((curr_page+1)) -- last-quick-sheet.pdf

# TODO killall quicksheets?
# it would be nice for it to be a "Refile area"
