#!/usr/bin/env bash
set -euo pipefail

docker run -it --rm \
    -v $HOME/.config/goosepaper:/goosepaper/mount \
    -v $HOME/.rmapy:/root/.rmapy \
    \ # -v $PWD:/goosepaper/out \
    j6k4m8/goosepaper \
    goosepaper -c mount/config.json --upload # -o out/Goosepaper.pdf
