#!/usr/bin/env bash
set -euo pipefail

goosedate=$(date +%F)

cd $(mktemp -d)
mkdir outdir
for doctheme in $(fd -e json . ~/.config/goosepaper -x echo {/.}); do
    docker rm -f gooserun
    docker run --name gooserun \
        -v $HOME/.config/goosepaper:/goosepaper/mount \
        j6k4m8/goosepaper \
        goosepaper -c=mount/$doctheme.json -o=out.pdf
    docker cp "gooserun:/goosepaper/out.pdf" "./outdir/$goosedate-daily-$doctheme.pdf"
done

if [[ -n ${JM_GOOSE_SIT:-""} ]]; then
    echo "Files at $PWD"
    exit 0
fi

mv ./outdir/* $HOME/Documents/remarkable/sink
