#!/usr/bin/env bash
set -euo pipefail

emailid="$1"

SENT_ARTICLES_DIR="$HOME/.local/run/remarkable-send-substack"

if [ -f "$SENT_ARTICLES_DIR/$emailid" ]; then
    echo "Already done"
    exit 1
fi

cd $(mktemp -d)

info=$(s notmuch extract-subject-and-html "$emailid")

jq -r .body <<<"$info" >./substack.html

pdfpath=$(s util html-to-pdf $(realpath ./substack.html))

author=$(jq -r .from <<<"$info" | sd '<.*>' '' | sd '^\s+' '' | sd '\s+$' '')

tgtname="$(jq -r .title <<<"$info" | sd ' ' '_').pdf"

mv "$pdfpath" "./$tgtname"

rmapi -ni mkdir "/substack/$author" || true
rmapi -ni put "$tgtname" "/substack/$author"
date >"$SENT_ARTICLES_DIR/$emailid"
