#!/usr/bin/env bash
set -euo pipefail

emailid="$1"

echo "Starting $emailid"

SENT_ARTICLES_DIR="$HOME/.local/run/remarkable-send-substack"

if [ -f "$SENT_ARTICLES_DIR/$emailid" ]; then
    echo "Already done"
    exit 1
fi

cd $(mktemp -d)

info=$(s notmuch extract-subject-and-html "$emailid")

jq -r .body <<<"$info" >./substack.html

pdfpath=$(s util html-to-pdf $(realpath ./substack.html))

author=$(jq -r .from <<<"$info" | sd '<.*>' '' | sd '^\s+' '' | sd '\s+$' '')

monthlist=(Jan Feb Mar Apr May Jun Ful Aug Sep Oct Nov Dec)
monthnumber() {
    cnt=0
    for el in "''${monthlist[@]}"; do
        [[ $el == "$1" ]] && echo $cnt && break
        ((++cnt))
    done
}
articledateinfo=$(jq -r .date <<<"$info" | choose 2 1 3)
articleyear=$(choose -1 <<<"$articledateinfo")
articleday=$(choose 1 <<<"$articledateinfo")
articlemonthstr=$(choose 0 <<<"$articledateinfo")
articlemonth=$(monthnumber "$articlemonthstr")
articledate="$articleyear-$articlemonth-$articleday"

tgtname="$articledate--$(jq -r .title <<<"$info").pdf"

mv "$pdfpath" "./$tgtname"

rmapi -ni mkdir "/substack/$author" 2>/dev/null || true
echo "Uploading $emailid"
rmapi -ni put "$tgtname" "/substack/$author"
date >"$SENT_ARTICLES_DIR/$emailid"
