#!/usr/bin/env bash
set -euo pipefail

emailid="$1"

echo "Starting $emailid"

cd $(mktemp -d)

info=$(s notmuch extract-subject-and-html "$emailid")

jq -r .body <<<"$info" >./email-body.html

pdfpath=$(s util html-to-pdf $(realpath ./email-body.html))

author=$(jq -r .from <<<"$info" | sd '<.*>' '' | sd '^\s+' '' | sd '\s+$' '')

monthlist=(Jan Feb Mar Apr May Jun Ful Aug Sep Oct Nov Dec)
monthnumber() {
    cnt=0
    for el in "${monthlist[@]}"; do
        [[ $el == "$1" ]] && echo $cnt && break
        ((++cnt))
    done
}
monthnumberpadded() {
    TEMP="000000$1"
    echo "${TEMP:(-2)}"
}

articledateinfo=$(jq -r .date <<<"$info" | choose 2 1 3)
articleyear=$(choose -1 <<<"$articledateinfo")
articleday=$(choose 1 <<<"$articledateinfo")
articlemonthstr=$(choose 0 <<<"$articledateinfo")
articlemonthtmp=$(monthnumber "$articlemonthstr")
articlemonth=$(monthnumberpadded "$articlemonthtmp")
articledate="$articleyear-$articlemonth-$articleday"

tgtname="$articledate--$(jq -r .title <<<"$info").pdf"

mv "$pdfpath" "./$tgtname"

rmapi -ni mkdir "/s-script/$author" 2>/dev/null || true
rmapi -ni rm "/s-script/$author/$tgtname" 2>/dev/null || true
set +e
rmapi -ni put "$tgtname" "/s-script/$author"
