#!/usr/bin/env bash
set -euo pipefail

fd -e ${JM_ORG_TANGLE_EXT:-org} $(xargs printf "--exclude=%s " <<<"$JM_ORG_TANGLE_EXCLUDE") . $1 -x emacs --batch --eval "(require 'org)" --eval '(org-babel-tangle-file "{}")'
