#!/usr/bin/env bash
set -euo pipefail

repo_name="${1:-"$(s util github get-repo-name-dwim)"}"

http --body "https://api.github.com/repos/$repo_name/releases/latest" |
	jq '.assets[]' |
	jq -s --arg keys_to_keep '["name", "size", "browser_download_url"]' '.[] | with_entries( select( .key as $k | any($keys_to_keep | fromjson[]; . == $k) ))' -c |
	s util filterApplicableReleaseAssets |
	s shell strip-blank-lines
