#!/usr/bin/env bash
set -euo pipefail

filter="($(echo "$*" | tr ' ' '|'))"

base_path="$HOME/.config/gitlabform"

cd "$base_path"

s util yq-merge-all $(fd --maxdepth=1 -t f . "$base_path" -x echo {/.} | rg "$filter") base
