#!/usr/bin/env bash
set -euo pipefail

https ciao.priv.$PRIMARY_PERSONAL_DOMAIN/checks.json | jq '.[].id' | xargs -I_ https DELETE ciao.priv.$PRIMARY_PERSONAL_DOMAIN/checks/_.json
cat ~/.config/custom/ciao-backup.json | jq '.[]' -c | xargs -I_ bash -c "https --print=B POST ciao.priv.$PRIMARY_PERSONAL_DOMAIN/checks.json<<<'_'"
