#!/usr/bin/env bash
set -euo pipefail

winid=$(xdotool selectwindow)

jo geo="$(xdotool getwindowgeometry $winid)" name="$(xdotool getwindowname $winid)" classname="$(xdotool getwindowclassname $winid)" | jq
