#!/usr/bin/env bash
set -uo pipefail

if docker node inspect $1 >/dev/null 2>&1; then
    docker node demote $1 2>/dev/null
    docker node rm -f $1
fi

s tailscale remove-device $1
# s misc minions-do-async 'rm -f .config/goss/tailscale-peers.yml'
# TODO remove ssh key from gitlab
