#!/usr/bin/env bash
set -euo pipefail

if ! docker ps | rg -q dbeaver-helper; then
    docker rm -f dbeaver-helper
    echo "Creating pg wormhole"
    docker run --name dbeaver-helper --network=cloud-public -d -p 5432:5432 alpine/socat TCP-LISTEN:5432,fork TCP:$PG_SELFHOSTED_ADDR
fi
