#!/usr/bin/env bash
set -euo pipefail

user=$1
pass=$2

s misc pgcli-mkwormhole

export PGPASSWORD=$(bw get password postgres-self-hosted)

psql -h 127.0.0.1 -U $(bw get username postgres-self-hosted) -c "INSERT INTO mqtt_user (username, password, salt, is_superuser) VALUES ('$user', '$(s util gen-sha256-auth "$pass")', NULL, false);" mqtt
