#!/usr/bin/env bash
set -euo pipefail

gum spin --spinner moon --title "Destroying old droplet docker node" -- sh -c "
docker node update $1 --availability=drain || true
docker node demote $1 || true
docker node rm -f $1 || true
"
gum spin --spinner pulse --title "Remove tailscale ip" -- bash -lc '
s tailscale remove-device $1
s misc minions-do-async "rm -f .config/goss/tailscale-peers.yml"
'

# TODO remove ssh key from gitlab
s docean kill-droplet $1
s misc mkdroplet $1
