#!/usr/bin/env bash
set -uo pipefail

docker node update $1 --availability=drain
docker node demote $1
docker node rm -f $1
s tailscale remove-device $1
s misc minions-do-async 'rm -f .config/goss/tailscale-peers.yml'
# TODO remove ssh key from gitlab
s docean kill-droplet $1
s misc mkdroplet $1
