#!/usr/bin/env bash
set -euo pipefail

sudo touch /media/jmccown/boot/ssh

s misc rasb-pi-setup-wifi $(bw get username "Apartment Wifi") $(bw get password "Apartment Wifi") | sudo tee /media/jmccown/boot/wpa_supplicant.conf
