#!/usr/bin/env bash
set -euo pipefail

s misc rpi-setup-new

echo "Eject/remove the raspberry pi sd card, and plugin the raspberry pi"

while ! s Yn "Done with the above?"; do
  echo "Take your time"
  sleep 1
done

sleep 120

s misc raspiusbnet

roomname="$(s util prompt-and-confirm "Room name for this assistant?")"
s misc pgcli-emqx-add-user "$roomname" roomassistant

sshpass -p raspberry ssh pi@raspberrypi.local $'
wget -O - https://gist.githubusercontent.com/mKeRix/88b7b81e9bca044f74de1dc51696efb2/raw/799a20bca44cc61d8f8ae93878f2f28af8365a69/getNodeLTS.sh | bash
echo \'PATH="$PATH:/opt/nodejs/bin"\' >> ~/.profile
source ~/.profile
sudo apt-get update -y && sudo apt-get install -y build-essential libavahi-compat-libdnssd-dev libsystemd-dev bluetooth libbluetooth-dev libudev-dev libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev

sudo npm i --global --unsafe-perm room-assistant

sudo setcap cap_net_raw+eip $(eval readlink -f `which node`)
sudo setcap cap_net_raw+eip $(eval readlink -f `which hcitool`)
sudo setcap cap_net_admin+eip $(eval readlink -f `which hciconfig`)

mkdir -p ~/room-assistant/config
'

sshpass -p raspberry ssh pi@raspberrypi.local "
cat <<EOF | tee ~/room-assistant/config/local.yml

global:
  instanceName: '$roomname'
  integrations:
    - homeAssistant
    - bluetoothClassic
    - bluetoothLowEnergy
homeAssistant:
  mqttUrl: 'mqtt://$PRIMARY_PERSONAL_DOMAIN:1883'
  mqttOptions:
    username: '$roomname'
    password: roomassistant

EOF

"

sshpass -p raspberry ssh pi@raspberrypi.local $'

cat <<EOF | sudo tee /etc/systemd/system/room-assistant.service
[Unit]
Description=room-assistant service

[Service]
Type=notify
ExecStart=/opt/nodejs/bin/room-assistant
WorkingDirectory=/home/pi/room-assistant
TimeoutStartSec=120
TimeoutStopSec=30
Restart=always
RestartSec=10
WatchdogSec=60
User=pi

[Install]
WantedBy=multi-user.target

EOF


sudo systemctl enable room-assistant.service
sudo systemctl start room-assistant.service

'
