#!/usr/bin/env bash
set -euo pipefail

sudo howdy disable 0 || true
rm -f ~/.config/monitors.xml
cp ~/monitors.xml-tinypilot-disabled ~/.config/monitors.xml
sudo rm -f ~gdm/.config/monitors.xml

sudo cp ~/.config/monitors.xml ~gdm/.config/

echo "Rebooting in 7 sec..."
sleep 7
sudo reboot
