#!/usr/bin/env bash
set -euo pipefail

sudo howdy disable 0 || true
connected_outputs=$(xrandr --query | grep " connected" | awk '{print $1}')

TINYPILOT_INPUT=DP-5

for output in $connected_outputs; do
    if [[ "$output" != "$TINYPILOT_INPUT" ]]; then
        xrandr --output "$output" --on
    else
        xrandr --output "$output" --off
    fi
done

# echo "Rebooting in 7 sec..."
# sleep 7
# sudo reboot
