#!/usr/bin/env bash
set -uo pipefail

sudo howdy disable 1 || true

connected_outputs=$(xrandr --query | grep " connected" | awk '{print $1}')

TINYPILOT_INPUT=DP-5

# Iterate through all connected outputs
for output in $connected_outputs; do
    if [[ "$output" != "$TINYPILOT_INPUT" ]]; then
        xrandr --output "$output" --off
    else
        xrandr --output "$output" --on
    fi
done


# echo "Rebooting in 7 sec..."
# sleep 7
# sudo reboot
