#!/usr/bin/env bash
set -uo pipefail

sudo howdy disable 1 || true
rm -f ~/.config/monitors.xml
cp ~/monitors.xml-tinypilot-only ~/.config/monitors.xml
sudo rm -f ~gdm/.config/monitors.xml

sudo cp ~/.config/monitors.xml ~gdm/.config/
if s Yn "Reboot to complete tinypilot setup?"; then
    sudo reboot
fi
