#!/usr/bin/env bash
set -euo pipefail

http --auth $DROPLOOP_TRAEFIK_USER:${DROPLOOP_TRAEFIK_PASS:-$(bw get password traefik)} jackdmc.com:7799/api/http/services |
    jq -c 'map(select(.serverStatus)) | map(select([ .serverStatus[] ] | any(contains("DOWN"))))[]'

