#!/usr/bin/env bash
set -euo pipefail

inputlist=$(mktemp)

fd . /mnt/Media/ --exclude=Pics -e mp4 -e mkv -e avi >$inputlist

s util resumable-filelist-process \
    "$inputlist" \
    "$(s which misc videogrep-maybe-transcribe-one)"
