#!/usr/bin/env bash
set -euo pipefail

THEME="${WALLPAPER_THEME:-"$(cat $HOME/.local/wallpaper-query || echo "")"}"

if [ -z "$THEME" ]; then
    $HOME/apps/styli.sh/styli.sh --gnome --termcolor --nitrogen --monitors 3
else
    $HOME/apps/styli.sh/styli.sh --gnome --termcolor --nitrogen --monitors 3 --search "$THEME"
fi

systemctl --user restart racket-notifs-email.service
