#!/usr/bin/env bash
set -euo pipefail

THEME="${WALLPAPER_THEME:-"$(cat $HOME/.local/wallpaper-query || echo "")"}"

if [ -z "$THEME" ]; then
    styli.sh --gnome --nitrogen
else
    styli.sh --gnome --nitrogen --search "$THEME"
fi
