#!/usr/bin/env bash
set -euo pipefail

THEME="${WALLPAPER_THEME:-"$(cat $HOME/.local/wallpaper-query 2>/dev/null || echo "")"}"

if [ -z "$THEME" ]; then
    styli.sh --gnome --nitrogen --directory $HOME/Pictures/mbkhd-panels-pirate
else
    styli.sh --gnome --nitrogen --search "$THEME"
fi

wal -i "$(gsettings get org.gnome.desktop.background picture-uri-dark | sd 'file://' '' | sd "'" '')" >/dev/null 2>&1
