#!/usr/bin/env bash
set -euo pipefail

REQ_URL="$(s gitlab request-Url)/projects/$(urlencode "$1")/pipelines/$2"

python - <<___EOF
import requests
from time import sleep
request_url = "$REQ_URL"
headers = {"Private-Token": "$LAB_CORE_TOKEN"}
api_res = requests.get(request_url, headers=headers).json()
cistatus = api_res.get('status', 'not-found')
print(cistatus)

___EOF

