#!/usr/bin/env bash
set -euo pipefail

existingRecord="$(sqlite3 ~/.local/gitlab-pipelines.db '.mode json' 'SELECT * FROM pipelines WHERE id='"$2"' LIMIT 1' || echo "")"
if [[ -n ${existingRecord:-""} ]]; then
    echo "$existingRecord" | jq '.[0]'
    exit 0
fi
REQ_URL="$(s gitlab request-Url)/projects/$(s util urlencode "$1")/pipelines/$2"

python - <<___EOF | tee | pipx run sqlite-utils insert --alter --pk id ~/.local/gitlab-pipelines.db pipelines -
import requests
import json
from time import sleep
request_url = "$REQ_URL"
headers = {"Private-Token": "$LAB_CORE_TOKEN"}
print(json.dumps(requests.get(request_url, headers=headers).json()))

___EOF
