#!/usr/bin/env bash
set -euo pipefail

latestPipelineId=$(s gitlab pipelines get-latest-for-branch)
prjid=$(s gitlab lookup-project-id-integer)

existingRecord="$(sqlite3 $SCRIPTS_LOCAL_DIR/gitlab-stuff.db 'SELECT id FROM pipelines WHERE project_id='"$prjid"' AND id='"$latestPipelineId"' LIMIT 1' 2>/dev/null || echo "")"

if [[ -z ${existingRecord:-""} ]]; then
    s gitlab this-project-request "pipelines/$latestPipelineId" | sqlite-utils insert --alter --pk id --replace $SCRIPTS_LOCAL_DIR/gitlab-stuff.db pipelines -
fi
existingRecordStatus="$(jq -r '.status' <<<"$existingRecord")"
if [[ ${existingRecordStatus:-""} = pending ]] || [[ ${existingRecordStatus:-""} = running ]]; then
    # fetch updated status
    s gitlab this-project-request "pipelines/$latestPipelineId" | sqlite-utils insert --alter --pk id --replace $SCRIPTS_LOCAL_DIR/gitlab-stuff.db pipelines -
fi

sqlite3 "$SCRIPTS_LOCAL_DIR/gitlab-stuff.db" '.mode json' 'SELECT * FROM pipelines WHERE project_id='"$prjid"' AND id='"$latestPipelineId"' LIMIT 1' | jq '.[0]'

# s gitlab pipelines stats job-details-dwim
