#!/usr/bin/env bash
set -euo pipefail

latestPipelineId=$(s gitlab pipelines get-latest-for-branch)
prjid=$(s gitlab lookup-project-id-integer)

s gitlab project-request "$prjid" "pipelines/$latestPipelineId" | sqlite-utils insert --alter --pk id --replace $SCRIPTS_LOCAL_DIR/gitlab-stuff.db pipelines -
