#!/usr/bin/env bash

printf "" >$CBI_HOSTALIASES
printf "%s\tvault.cbinsights.local\n%s\tconsul.cbinsights.local\n" $(direnv exec ~/cbinsights s util resolve-first-ip $VAULT_HOST) $(direnv exec ~/cbinsights s util resolve-first-ip $CONSUL_HOST) >>$CBI_HOSTALIASES
