#!/usr/bin/env bash
set -euo pipefail

originurl=$(git remote get-url origin)

if [[ -z $originurl ]]; then
  echo "No git origin remote"
  exit 1
fi

gitlabInstanceDomain=$(s util strip_all $(s gitlab host-Url) "https://")
result=$(s util strip_all $(s util strip_all "$originurl" "git@""$gitlabInstanceDomain"":") ".git")

echo "$result" | rev | cut -d/ -f1 | rev
