#!/usr/bin/env bash
set -euo pipefail

jiraticket=${1:-"$(s jira select-active-ticket-dwim)"}

knownName=$(s cbi get-branchname-for-ticket "$jiraticket")

if [[ -z "$knownName" ]]; then
    newname=$(s cbi make-branchname "$jiraticket")
    s cbi set-branchname-for-ticket "$newname" "$jiraticket"
    echo "$newname"
else
    echo "$knownName"
fi
