#!/usr/bin/env bash
set -o pipefail

oldGossServePid=$(lsof -i :7321 | tail -n 1 | awk '{ print $2 }')
if [ -n "$oldGossServePid" ]; then kill -9 "$oldGossServePid"; fi

goss serve --gossfile ~/cbinsights/local-service/goss.yaml --listen-addr ":7321" >/dev/null 2>&1 &

while true; do
    echo "Checking connections: $(date)"
    error_info=$(curl --silent -H "Accept: application/json" 127.0.0.1:7321/healthz | jq -r '.results | map(select(.successful | not)) | map(if .meta==null then .["summary-line"] else (.meta | to_entries | map("\(.key): \(.value)") | add) end) | .[]')
    if [[ -n "$error_info" ]]; then
        dunstify --appname=cbigosscheck --replace=89658983 --timeout=100000 "CBI Local Service error!" "$error_info"
    fi
    sleep 30s
done
