#!/usr/bin/env bash
set -euo pipefail
PROJECT_LIST=()
collecting_prjs=1
most_recent_id=0
while [[ $collecting_prjs -eq 1 ]]; do
	collecting_prjs=0
	for prj_info in $(s gitlab request "groups/16/projects" sort==asc order_by==id id_after==$most_recent_id | jq -c '.[] | "\(.id)_\(.name)"' | tr -d '"'); do
		collecting_prjs=1
		PROJECT_LIST+=($prj_info)
	done
	most_recent_prj="${PROJECT_LIST[-1]}"
	most_recent_id=$(echo "$most_recent_prj" | cut -d_ -f1)
done
echo "$PROJECT_LIST" | tr '[[:space:]]' '\n' | map split _ | map at 1
