#!/usr/bin/env bash
set -euo pipefail

jiraticket=${1:-"$(s jira select-active-ticket-dwim)"}

ticketdesc=$(gum input --placeholder "$msg" --value $(jira get-details "$jiraticket" | jq .fields.summary) | sd ' ' '-')

echo "$jiraticket-$ticketdesc"
