#!/usr/bin/env bash
set -euo pipefail

activeTicket=$(s jira get-active-ticket)
if [ -n "$activeTicket" ] && gum confirm "Continue with active jira ticket? ($activeTicket)"; then
  echo "Starting last ticket"
  s cbi start-last-ticket
else
  echo "Could not determine previous jira ticket"
fi
