#!/usr/bin/env bash
set -euo pipefail

if [[ -n ${CBI_NOMAD_USE_PROD:-""} ]]; then
  NOMAD_ADDR="https://nomad-prd.cbinsights.com" nomad $*
  exit 0
fi

currenv=$(s cbi local curr-env-dwim)
currbranch=$(git rev-parse --abbrev-ref HEAD)

if [[ $currenv = "dev" ]]; then
  if [[ $currbranch = "staging" ]]; then
    echo "Warning branch env mismatch! Maybe you want to connect to staging?" >>/dev/stderr
  fi
fi

if [[ $currenv = "stg" ]]; then
  if [[ $currbranch = "develop" ]]; then
    echo "Warning branch env mismatch! Maybe you want to connect to develop?" >>/dev/stderr
  fi
fi

nomad $*
