#!/usr/bin/env bash
set -euo pipefail

target_service_name=${1:-$(s cbi svc select-dwim)}

if [ -z $target_service_name ]; then
  echo "Must provide a service name"
  exit 1
fi

if [ $target_service_name = cbi-site ]; then
  tmuxinator start cbi-site $target_service
  exit 0
fi

if [[ $# -gt 0 ]]; then shift; fi

target_service=
if [ -d $HOME/cbinsights/gitlab.cbinsights.com/engineering/services/$target_service_name ]; then
  target_service=$HOME/cbinsights/gitlab.cbinsights.com/engineering/services/$target_service_name
fi

target_service=$(realpath --relative-base $HOME/cbinsights "$target_service")

if [ -f ~/cbinsights/$target_service/go.mod ]; then
  tmuxinator start cbi-golang-service $target_service_name
  exit 0
fi

if [ -f ~/cbinsights/$target_service/src/setup.cfg ]; then
  tmuxinator start cbi-python-service $target_service_name
  exit 0
fi

echo "Unsupported service type?"
exit 1
