#!/usr/bin/env bash
set -euo pipefail

s work ensure-local-ticket-matches-jira-board

if ! s jira ticket-is-incomplete; then
  s jira change-active-ticket
fi

currticket="$(s jira select-active-ticket-dwim)"
if [[ -n "$currticket" ]]; then
  s cbi work-on "$currticket"
fi
