#!/usr/bin/env bash
set -euo pipefail

echo "auto gen envrc"
echo '
source_up
use cbirepovars
' >.envrc
direnv allow

consul services register -http-addr=http://localhost:8500 -name $SVC_NAME -address $(hostname) -port 50051
trap "consul services deregister -id=$SVC_NAME" SIGINT

if [[ -f go.mod ]]; then
    echo "Starting go repo"
    fd -e go | entr -r go run main.go
fi

if [[ -f src/live_reload.py ]]; then
    echo "Starting python repo"
    cd src
    python live_reload.py
fi
