#!/usr/bin/env bash
set -euo pipefail

# echo "BYPASSING RUN ON HOST TO RUN IN DOCKER"
# make
# exit 0

echo "auto gen envrc"
echo "
source_up
use cbirepovars
export GRPC_PORT=$(s util find-open-port)
" >.envrc
direnv allow

consul services register -http-addr=http://localhost:8500 -name $SVC_NAME -address $MY_LAN_IP -port $GRPC_PORT
trap "consul services deregister -id=$SVC_NAME" SIGINT

if [[ -f go.mod ]]; then
    echo "Starting go repo"
    fd -e go | entr -r go run main.go
fi

if [[ -f src/live_reload.py ]]; then
    echo "Starting python repo"
    cd src
    python live_reload.py
fi
