#!/usr/bin/env bash
set -euo pipefail

tmuxinator start cbi-local-service

s cbi wait-for-active-local-service

jiraticket=$(s jira select-active-ticket-dwim "${1:-""}")

# ensure branchname has been setup
s cbi get-branchname-dwim "$jiraticket" >/dev/null

jiraLookupKnownReposFn() {
    sqlite3 "$JIRA_HELPER_DB" "SELECT repo FROM ticket_repos WHERE ticket=\"$jiraticket\""
}

export -f jiraLookupKnownReposFn

if [[ -z "$(jiraLookupKnownReposFn)" ]]; then
    s cbi ticket add-related-repos "$jiraticket"
fi

s cbi ticket start-relevant-services "$jiraticket"
