#!/usr/bin/env bash
set -euo pipefail

jiraticket=$(s jira select-active-ticket-dwim "${1:-""}")

# ensure branchname has been setup
s cbi get-branchname-dwim "$jiraticket" >/dev/null

jiraLookupKnownReposFn() {
    sqlite3 "$JIRA_HELPER_DB" "SELECT repo FROM ticket_repos WHERE ticket=\"$jiraticket\""
}

export -f jiraLookupKnownReposFn

if [[ -z "$(jiraLookupKnownReposFn)" ]]; then
    for r in $(s cbi svc select-many); do
        jo ticket="$jiraticket" repo="$r" | sqlite-utils insert "$JIRA_HELPER_DB" ticket_repos -
    done
fi

jiraLookupKnownReposFn | tee | xargs -n1 s cbi start-service
