#!/usr/bin/env bash
set -euo pipefail

# [[https://developer.chrome.com/docs/extensions/mv3/external_extensions/][chrome docs]]

destpath="$HOME/.local/crx/$1-$(date +%s).crx"

jo external_crx="$destpath" external_version=${2:-"0.0.0"} | jq

# jo external_update_url="https://web-ext-server.jackdmc.com/$1" | jq
