#!/usr/bin/env bash
set -euo pipefail

# [[https://developer.chrome.com/docs/extensions/mv3/external_extensions/][chrome docs]]

# destpath="$HOME/.local/crx/$1-$(date +%s).crx"
# external_crx="$destpath" external_version=${2:-"0.0.0"}
jo external_update_url="https://jackmac92.gitlab.io/${1:-$CI_PROJECT_NAME}/update.xml" | jq
