#!/usr/bin/env bash
set -euo pipefail

rm -f ~/Downloads/build.zip
curDir=${1:-${PWD##*/}}
xdg-open "$(s web-ext get-latest-release-asset-url "jackmac92/$curDir")"
sleep 4
rm -rf ~/.local/unpacked-extensions/$curDir
unzip ~/Downloads/build.zip -d ~/.local/unpacked-extensions/$curDir
