#!/usr/bin/env bash
set -euo pipefail

REQ_URL="$(s gitlab request-Url)/projects/$(urlencode "$1")/pipelines/$2"

python - <<___EOF
import requests
from time import sleep
request_url = "$REQ_URL"
headers = {"Private-Token": "$LAB_CORE_TOKEN"}
cistatus = "pending"
while cistatus in ["pending", "running"]:
    api_res = requests.get(request_url, headers=headers).json()
    cistatus = api_res.get('status')
    # if cistatus is None:
    #     print("Error!, no status in api_res\n{0}\nCalling '{1}'".format(api_res, request_url))
    sleep(3)
print(cistatus)
___EOF
