#!/usr/bin/env bash
set -euo pipefail

REQ_URL="$(s gitlab request-Url)/projects/$(s util urlencode "$1")/pipelines/$2"

python - <<___EOF
import requests
import requests_cache
from datetime import timedelta

from time import sleep
request_url = "$REQ_URL"
headers = {"Private-Token": "$LAB_CORE_TOKEN"}
cistatus = "pending"
session = requests_cache.CachedSession('gitlab_pipeline_cache', expire_after=timedelta(seconds=10))

while cistatus in ["pending", "running"]:
    api_res = session.get(request_url, headers=headers).json()
    cistatus = api_res.get('status')
    sleep(3)
print(cistatus)
___EOF
