#!/usr/bin/env bash
set -euo pipefail

pipeline_sha="$1"
repo_remote_url="$2"

REQ_URL="$(s gitlab request-Url)/projects/$(urlencode "$1")/pipelines/$2"

s gitlab pipelines get-id-from-head-commit

python - <<___EOF
import requests
import requests_cache
from datetime import timedelta

from time import sleep
request_url = "$REQ_URL"
headers = {"Private-Token": "$LAB_CORE_TOKEN"}
cistatus = "pending"
session = requests_cache.CachedSession('gitlab_pipeline_cache', expire_after=timedelta(seconds=10))

while cistatus in ["pending", "running"]:
    api_res = session.get(request_url, headers=headers).json()
    cistatus = api_res.get('status')
    sleep(3)
print(cistatus)
___EOF
