#!/usr/bin/env bash
set -euo pipefail

notititle="$1"
notitext="$2"
notiurl="${3}"
notitype="${4:-blank}"

jo title="$notititle" \
   text="$notitext" \
   devices="$PUSHCUT_DEVICES" \
   defaultAction="$(jo url="$notiurl")" |
   http -A creds POST "$PUSHCUT_API_URL/notifications/$notitype"
