#!/usr/bin/env bash
set -euo pipefail

notitext="$1"
notititle="${2:-$(cut -d $' ' -f1 <<<"$1")}"

jo "title=$notititle" \
   "text=$notitext" \
   "devices=$PUSHCUT_DEVICES" \
   actions="$(
      jo -a \
         "$(jo url="http://$(s tailscale this-device-ip):8080" \
            name="Yes" \
            urlBackgroundOptions=$(jo \
               httpContentType="application/json" \
               httpBody=$(jo data=$(jo result=true) | jq 'tostring') \
               httpHeader=$(jo -a $(jo key="MY-SECRET-HEADER" value="$RANDOM-VALUE")) \
               httpMethod="POST"))" \
         "$(jo url="http://$(s tailscale this-device-ip):8080" \
            name="No" \
            urlBackgroundOptions=$(jo \
               httpContentType="application/json" \
               httpBody=$(jo data=$(jo result=false) | jq 'tostring') \
               httpHeader=$(jo -a $(jo key="MY-SECRET-HEADER" value="$RANDOM-VALUE")) \
               httpMethod="POST"))"
   )"
