#!/usr/bin/env bash
set -euo pipefail

notititle="$1"
notitext="$2"
notiurl="${3}"
notitype="${4:-blank}"

# TODO: extract url from below
# gotty -r -w --title-format pushcut-term tmux new-session -t $THIS_TMUX_SESSION

jo title="$notititle" \
   text="$notitext" \
   devices="$(jo -a "jacks iphone")" \
   defaultAction="$(jo url="$notiurl")" |
   http -A creds POST "$PUSHCUT_API_URL/notifications/$notitype"
