#!/usr/bin/env bash
set -euo pipefail
gitlabInstanceDomain=$(strip_all $GITLAB_INSTANCE_URL "https://")
result=$(strip_all $(strip_all $(git remote get-url origin) "git@""$gitlabInstanceDomain"":") ".git")
echo "$result"
