#!/usr/bin/env bash
set -euo pipefail

prjid="$1"
tgtPipelineId="$2"

export TARGET_GITLAB_PROJECT="$prjid"

s gitlab project-request "$prjid" "pipelines/$tgtPipelineId" |
    sqlite-utils insert --alter --pk id --replace "$SCRIPTS_LOCAL_DIR/gitlab-stuff.db" pipelines -
