#!/usr/bin/env bash
set -euo pipefail

sha=$1
ref=$(git current-branch)
lastCommitPipelineId=""
attempts=0

while [ -z ${lastCommitPipelineId:-""} ]; do
    lastCommitPipelineId=$(s gitlab this-project-request "pipelines" sha=="$sha" ref=="$ref" | jq '.[0].id')
    attempts=$(($attempts + 1))
    if ! [ -z $lastCommitPipelineId ]; then
        break
    fi
    if [ $attempts -gt 5 ]; then
        exit 1
    fi
    sleep 0.75
done

echo "$lastCommitPipelineId"
