#!/usr/bin/env bash
set -euo pipefail

ref="${1:-"$(git current-branch)"}"

lastCommitPipelineId=""
attempts=0

while [ -z ${lastCommitPipelineId:-""} ]; do
    lastCommitPipelineId=$(s gitlab this-project-request "pipelines" ref=="$ref" | jq '.[0].id')
    attempts=$(($attempts + 1))
    if ! [ -z $lastCommitPipelineId ]; then
        break
    fi
    if [ $attempts -gt 5 ]; then
        s gitlab lookup mr-last-pipeline-id
    fi
    sleep 0.75
done

echo "$lastCommitPipelineId"
