#!/usr/bin/env bash
set -euo pipefail

s gitlab pipelines list-new-for-current-project |
    jq -r '.[] | "s gitlab pipelines fetch-and-save-pipeline \(.project_id) \(.id)"' |
    xargs -n 1 -d $'\n' bash -c
