#!/usr/bin/env bash
set -euo pipefail
echo "Needs sudo"
sudo echo "Thanks"
zinit update
zinit cclear
rustup update
nix-channel --update
home-manager switch
[ -f ~/.emacs.d/bin/doom ] && ~/.emacs.d/bin/doom -y upgrade
sudo apt-get update -y
sudo apt-get upgrade -y
