#!/usr/bin/env bash
set -euo pipefail

tgt=${PWD##*/}

s racket install-deps-here
raco exe -o $tgt ${RACKET_ENTRYPOINT:-main.rkt}
exefile=$PWD/$tgt
cd $(mktemp -d)
mv -f $exefile app
raco dist $tgt app
mkdir -p ~/.local/racket-apps/
rm -rf ~/.local/racket-apps/$tgt
mv $tgt ~/.local/racket-apps/
rm -f ~/.local/bin/$tgt
ln -s ~/.local/racket-apps/$tgt/bin/app ~/.local/bin/$tgt
