#!/usr/bin/env bash
set -euo pipefail

tgt=$1

raco exe $tgt.rkt
exefile=$PWD/$tgt
cd $(mktemp -d)
mv -f $exefile app
raco dist $tgt app
mkdir -p ~/.local/racket-scripts/
rm -rf ~/.local/racket-scripts/$tgt
mv $tgt ~/.local/racket-scripts/
rm -f ~/.local/bin/$tgt
ln -s ~/.local/racket-scripts/$tgt/bin/app ~/.local/bin/$tgt
