#!/usr/bin/env bash
set -euo pipefail

tgt=${PWD##*/}
if [[ $tgt = href-router-racket ]]; then
    tgt=href-router
fi

s racket install-deps-here
raco exe -o $tgt ${RACKET_ENTRYPOINT:-main.rkt}
exefile=$PWD/$tgt
cd $(mktemp -d)
mv -f $exefile app
raco dist $tgt app
mkdir -p ~/.local/racket-apps/
rm -rf ~/.local/racket-apps/$tgt
mv $tgt ~/.local/racket-apps/
s racket mk-local-bin-exe $tgt
