#!/usr/bin/env bash
set -euo pipefail

tgt=$1

s racket install-deps-here
raco exe $tgt.rkt
exefile=$PWD/$tgt
cd $(mktemp -d)
mv -f $exefile app
raco dist $tgt app
mkdir -p ~/.local/racket-scripts/
rm -rf ~/.local/racket-scripts/$tgt
mv $tgt ~/.local/racket-scripts/
s racket mk-local-bin-exe $tgt
