#!/usr/bin/env bash
set -euo pipefail

tgt=$1

s racket install-deps-here
raco exe $tgt.rkt
exefile=$PWD/$tgt
cd $(mktemp -d)
mv -f $exefile app
raco dist $tgt app
mkdir -p ~/.local/racket-scripts/
rm -rf ~/.local/racket-scripts/$tgt
mv $tgt ~/.local/racket-scripts/
rm -f ~/.local/bin/$tgt
echo "
#!/usr/bin/env sh

~/.local/racket-scripts/$tgt/bin/app \$*
" >~/.local/bin/$tgt
chmod +x ~/.local/bin/$tgt
