#!/usr/bin/env python3

import libtmux
import sys
from pathlib import Path


server = libtmux.Server()


def get_pane_cwd(p):
    return p.display_message("#{pane_current_path}", True)[0]


def is_parent(parent_path, child_path):
    return Path(child_path).is_relative_to(parent_path)


def create_pane_identifier(p):
    """Strips the $@% symbols and prints joined by ':'"""
    sess = p.session.id.replace("$", "")
    win = p.window_id.replace("@", "")
    pane = p.id.replace("%", "")
    return f"{sess}:{win}:{pane}"


def main():
    tgt = Path(sys.argv[1])
    for p in server.sessions[0].panes:
        pane_path = get_pane_cwd(p)
        if is_parent(tgt, pane_path):
            print(create_pane_identifier(p))
            return None
    else:
        print("No pane found")


if __name__ == "__main__":
    if len(sys.argv) < 2:
        raise Exception("Requries an argument path to locate the pane for")
    main()
