#!/usr/bin/env bash
set -euo pipefail

vpsname="$1"

echo "Installing tailscale"
cat ~/.local/share/chezmoi/.chezmoiscripts/run_once_install-tailscale.sh.tmpl | CHEZ_WITH_SUDO=1 chezmoi execute-template | s docean sshcmd-via-doctl "$vpsname" root "bash -"
echo "Registering tailscale"
cat ~/.local/share/chezmoi/.chezmoiscripts/run_once_after_tailscale-auth.sh.tmpl | CHEZ_WITH_SUDO=1 chezmoi execute-template | s docean sshcmd-via-doctl "$vpsname" root "bash -"
echo "Updating tailscale IP"
s misc chezmoi-update-one-tailscale-ip "$vpsname" || true
s util until-cmd-passes ssh -o StrictHostKeyChecking=accept-new "root@$(s tailscale get-ip "$vpsname")" "echo hi"
echo "SSH via tailscale IP complete!"
