#! /usr/bin/env bash
set -euo pipefail

cbienv=${1:-$(s cbi env-select-dwim)}
targetDb=${2:-"main"}
DBHOST=""
DBSUFFIX=""
if [ "$targetDb" = "main" ]; then
	DBTABLE="cbi_data"
	DBSUFFIX="-$cbienv"
	if [ $cbienv = "stg" ]; then
		DBSUFFIX="-staging"
	fi
	if [ $cbienv = "prd" ]; then
		DBSUFFIX=""
	fi
	DBHOST="mysql$DBSUFFIX.cbinsights.com"
elif [ "$targetDb" = "table" ]; then
	if [ $cbienv = "dev" ]; then
		DBHOST="rds-cbi-dev-table-service.cluster-cldspmgmf8rw.us-east-1.rds.amazonaws.com"
	fi
	if [ $cbienv = "stg" ]; then
		DBHOST="rds-cbi-stg-table-service.cluster-cwk1jdpnshja.us-west-2.rds.amazonaws.com"
	fi
	if [ $cbienv = "prd" ]; then
		DBHOST="rds-cbi-prd-table-service.cluster-cwk1jdpnshja.us-west-2.rds.amazonaws.com"
	fi
fi

echo "$DBHOST"
