#! /usr/bin/env bash
set -euo pipefail

mycli --login-path "prd-main" --csv -e "
        SELECT u.email, u.id_user
        FROM cbi_user.cbi_user u
        WHERE u.email = $1" | s util convert-csv-to-json | s fzf select-by-json-key "email" | jq -r '.id_user'
