#!/usr/bin/env bash
set -euo pipefail

if [[ -z "${CBI_ENV:-""}" ]]; then
  export CBI_ENV="$1"
fi

if [[ -n "${CBI_REMOTE_LOCAL_SVC:-""}" ]]; then
  ssh -t ${CBI_LOCAL_DEV_ENVOY_HOST:-""} cbi local $CBI_ENV
  exit 0
fi

cbi local $CBI_ENV
