#!/usr/bin/env bash
set -euo pipefail

. ./.cbivenv/bin/activate

echo "Installing proto"
# feed the proto_requirements.txt file into the while loop and iterate over each line
# the || in the while loop prevents missing the last line if there is no newline in the requirements file
# (apparently C stdin expects all text files to end in newline)
while read -r line || [ -n "$line" ]; do
    # ignore blank and comment lines
    if [[ -n "$line" ]] && [[ "$line" != \#* ]]; then
        if [[ $line == *:* ]]; then
            servicename=$(echo "$line" | cut -d ':' -f1)
        else
            servicename=$(echo "$line" | cut -d '/' -f1)
        fi

        echo "$(pwd)"
        if [ "$servicename" != "tagger" ] && [ "$servicename" != "cbinsights" ] && [ "$servicename" != "google" ] && [ "$servicename" != "swagger" ]; then
            proto_path="cbinsights.$servicename.$servicename"
            python -c "from cbi.grpc import proto_find_and_compile; proto_find_and_compile('$proto_path');"
            echo "Compiled $servicename"
        fi
    fi
done <proto_requirements.txt
