#!/usr/bin/env bash
set -euo pipefail

python setup.py egg_info
cat python_service_utils.egg-info/requires.txt | rg -v '\[' >reqs.txt
pip install --extra-index-url https://__token__:$PYPI_TOKEN@gitlab.cbinsights.com/api/v4/projects/611/packages/pypi/simple -r reqs.txt
