#!/usr/bin/env bash
set -euo pipefail

export BUILDING_SELF=True
VERSION=$(python setup.py --version 2>/dev/null)
python setup.py sdist bdist_wheel
twine check dist/*
python -m twine upload --verbose --repository gitlab dist/*
git tag -a ${VERSION} -m "${VERSION} Tagged for local publish"
git push origin $VERSION -o ci.skip
