#!/usr/bin/env bash
set -euo pipefail

s gitlab list-renovate-mrs | jq -r '.[] | select(.title == "Configure Renovate") | "/projects/\(.project_id)/merge_requests/\(.iid)/merge"' | xargs -n 1 -d $'\n' s gitlab request PUT

