#!/usr/bin/env bash
set -euo pipefail

full_url="${1:-""}"

if echo "$full_url" | grep -q "cbinsights"; then
	s bitwarden get-field "CBI gitlab" general-use-token
else
	s bitwarden get-field "gitlab.com" cli-api-token
fi
