#!/usr/bin/env bash
set -euo pipefail

remote_val="${1:-"$(git remote get-url origin)"}"
remote_val=$(sd "ssh://" "" <<<"$remote_val")
remote_val=$(sd ".com/" ".com:" <<<"$remote_val")

gitlabInstanceDomain=$(s util strip_all $GITLAB_INSTANCE_URL "https://")
result=$(s util strip_all $(s util strip_all $remote_val "git@""$gitlabInstanceDomain"":") ".git")
echo "$result"
