#!/usr/bin/env bash
set -euo pipefail

reponame=$(s gitlab get-gitlab-project-name-from-remote)
cd $(mktemp -d)

if [[ $# > 1 ]]; then
    s util gitlabformgen-noninteractive $* >./config.yml
else
    s util gitlabformgen $* >./config.yml
fi

cat config.yml
echo "Updating for $reponame"

GITLAB_TOKEN=$GITLAB_API_TOKEN pipx run gitlabform "$reponame"
