#!/usr/bin/env bash
set -euo pipefail

prjname="${1:-$(s gitlab get-gitlab-project-name-from-remote)}"

sqlite3 "$SCRIPTS_LOCAL_DIR/gitlab-stuff.db" "SELECT id FROM repositories WHERE path_with_namespace LIKE '$prjname' LIMIT 1" || echo ""
