#!/usr/bin/env bash
set -euo pipefail

reqflags=()

while [[ $1 = --* ]]; do
	reqflags+=("$1")
	shift
done

gitlab_project=$1
shift

req_verb_arg="${1:-""}"

if [[ $req_verb_arg = "POST" ]] || [[ $req_verb_arg = "GET" ]] || [[ $req_verb_arg = "PUT" ]] || [[ $req_verb_arg = "DELETE" ]] || [[ $req_verb_arg = "HEAD" ]]; then
	req_method=$req_verb_arg
	shift
else
	req_method="GET"
fi

api_path="${1:-""}"
if [[ $# -gt 0 ]]; then shift; fi

req_path="projects/$(s util urlencode "$gitlab_project")/$api_path"

s gitlab request ${reqflags[@]} "$req_method" "$req_path" $*
