#!/usr/bin/env bash
set -euo pipefail

project_name="${1:-"$(s util prompt-and-confirm "Provide a project name")"}"

template="${2:-"$(s gitlab request "groups/5776495/projects" | jq -r '.[].path' | fzf)"}"

output_parent_dir="$HOME/Projects/gitlab.com/jackmac92"
output_dir="$output_parent_dir/$project_name"
output_dir_link="$HOME/Projects/from-template/$template/$project_name"

mkdir -p "$HOME/Projects/from-template/$template"

if [[ "$template" =~ "cookiecutter" ]]; then
	cruft create "https://gitlab.com/quickstart-templates/$template" --output-dir "$output_parent_dir/" --extra-context "$(jo project_name="$project_name")"
	cd "$output_dir"
	git init
else
	cd "$output_parent_dir"
	git clone "git@gitlab.com:quickstart-templates/""$template"".git" "$project_name"
	cd "$project_name"
	git remote rename origin upstream
fi

ln -s "$output_dir" "$output_dir_link"

s gitlab create-remote-repo

chronic git commit --allow-empty --no-verify -m 'repo setup/init'
chronic git push -u origin "$(git current-branch)" -o ci.skip

if [[ ! "$template" =~ "cookiecutter" ]]; then
	s gitlab handle-new-repo-setup "$project_name"
fi

s gitlab gitlabform-by-template "$template"

echo "All the important stuff is done, registering repo locally"

cd "$output_dir"

s git register-repo

cd "$output_dir"
