#!/usr/bin/env bash
set -euo pipefail

s gitlab list-all-work-projects | jq '"git clone \(.ssh_url_to_repo) ~/cbinsights/gitlab.cbinsights.com/\(.path_with_namespace) 2>/dev/null || true"' | xargs -n 1 bash -c

cd ~/cbinsights/gitlab.cbinsights.com/
s git mirrorfleet 's git register-repo'
