#!/usr/bin/env bash
set -euo pipefail

reqflags=()

while [[ $1 = --* ]]; do
	reqflags+=("$1")
	shift
done

if [[ $1 = "POST" ]] || [[ $1 = "GET" ]] || [[ $1 = "PUT" ]] || [[ $1 = "DELETE" ]] || [[ $1 = "HEAD" ]]; then
	req_method=$1
	shift
else
	req_method="GET"
fi

req_path="$1"
shift
full_url=$(s gitlab request-Url "$req_path")

if [ -n ${GITLAB_REQUEST_DEBUG:-""} ]; then
	set -x
fi

http --ignore-stdin --check-status --body ${reqflags[@]} "$req_method" "$full_url" Private-Token:"$LAB_CORE_TOKEN" $* ${JM_GITLAB_REQ_EXTRA_PARAMS:-}

if [ -n ${GITLAB_REQUEST_DEBUG:-""} ]; then
	set +x
fi
