#!/usr/bin/env bash
set -euo pipefail

jo \
    title="${SSH_KEY_TITLE:-"s script sshkey $(date)"}" \
    key="${SSH_KEY_TO_ADD:-"$(cat ~/.ssh/id_rsa.pub)"}" |
    s gitlab request-stdin POST "/user/keys"
