#!/usr/bin/env bash
set -euo pipefail

public_ip="$1"

for i in $(seq 4); do
  # Make sure this happens, seems to skip it for some reason sometimes
  chronic ssh "root@$public_ip" "
sudo cp /root/.ssh/authorized_keys /home/jmccown/.ssh/authorized_keys
sudo chmod 600 /home/jmccown/.ssh/authorized_keys
sudo chown jmccown:jmccown /home/jmccown/.ssh/authorized_keys
"
done
