#!/usr/bin/env bash
set -euo pipefail

proto_path=${1:-"$(s cbi svc-name-to-proto-path "$(s cbi svc select-dwim)")"}
import_path="$(s cbi proto walkup-for-import-path "$proto_path")"
rpc_method="${2:-"$(s proto pick-rpc "$proto_path")"}"

svc_name=$(cat "$proto_path" | s proto get-svc-name-from-file)
pkg_name=$(cat "$proto_path" | s proto get-pkg-name-from-file)

grpcurl -import-path "$import_path" -proto "$proto_path" describe "$pkg_name.$svc_name.$rpc_method" | tail -n 1 | rg -o 'rpc\s\w+\s\(\s(\.\S+)\s\)\sreturns\s\(\s(\.\S+)\s\)' -r '$1
$2'

## returns:
# requestMessage
# responseMessage
