#!/usr/bin/env bash
set -euo pipefail

bw get template item |
    jq --arg itemname "$1" --arg pass "${2:-"$(bw generate)"}" '. + {name: $itemname, login: { password: $pass }}' |
    bw encode |
    bw create item
