#!/usr/bin/env bash
set -euo pipefail

bw get template item |
    jq --arg itemname "$1" --arg noteval "$2" '. + {type: 2, name: $itemname, secureNote: { type: 0 }, notes: $noteval}' |
    bw encode |
    bw create item
