#!/usr/bin/env bash
set -euo pipefail

vpsname=$1

bitwardenSignin() {
    ssh -t "$vpsname" "
. /etc/profile # adds nix to path
bw login jackmac92@protonmail.com
export BW_SESSION=\"\$(bw unlock --raw ${BW_PASSWORD:-$(secret-tool lookup password bitwarden-primary)})\"
touch /tmp/bw-auth
echo
echo \"export BW_SESSION=\$BW_SESSION\" | tee /tmp/bw-auth
source /tmp/bw-auth
"
}

chronic ssh "$vpsname" "rm -rf ~/.bw-auth ~/.config/Bitwarden\ CLI"
bitwardenSignin
