#!/usr/bin/env bash
set -euo pipefail

vpsname=$1

bitwardenSignin() {
    ssh -t "$vpsname" "
. /etc/profile # adds nix to path
export PATH=\$PATH:/opt/homebrew/bin/
BW_CLIENTID=user.fc84d6d5-9ada-4210-a68f-a9f4003df894 BW_CLIENTSECRET=${BW_CLIENTSECRET:-$(secret-tool lookup password bitwarden-client-secret)} bw login jackmac92@protonmail.com --apikey
export BW_SESSION=\"\$(bw unlock --raw ${BW_PASSWORD:-$(secret-tool lookup password bitwarden-primary)})\"
touch /tmp/bw-auth
echo
echo \"export BW_SESSION=\$BW_SESSION\" | tee /tmp/bw-auth
source /tmp/bw-auth
"
}

chronic ssh "$vpsname" "rm -rf ~/.bw-auth ~/.config/Bitwarden\ CLI"
bitwardenSignin
