#!/usr/bin/env bash
set -euo pipefail

exclude=${1:-"____unmatchable____"}
LIMIT=${2-1}

query='
SELECT command FROM invocations'"
WHERE command NOT LIKE '%$exclude%'
LIMIT $LIMIT
"

echo "$query"

# WHERE ='"$prjid"' AND id='"$latestPipelineId"' LIMIT 1'

sqlite3 $SCRIPTS_LOCAL_DIR/s-scripts-meta.db "$query"

# fd --hidden 'invocations' ~/.local/scripts-dir-metrics -x bash -c 'echo {}/* | tr " " "\n"' |
#     rg -v '\*$' |
#     choose -o _z_ -f / 4: |
#     choose -o _z_ -f _z_ -- -1 :-2 |
#     sed -e 's/invocations$//g' |
#     rg -v "$exclude" |
#     rg -v 'meta last-(executed|invoked)$' |
#     sort -n |
#     tail -n $LIMIT |
#     while read -r; do
#         fullpath=$(echo "$REPLY" | choose -f _z_ -o / 2:-1 | xargs printf "/%s")
#         s meta script-path-to-name "$fullpath"
#     done
