#! /usr/bin/env bash
set -euo pipefail

cbienv=${1:-$(s cbi local curr-env-dwim)}
targetDb=${2:-"main"}
credsPath=$(s cbi db auth latest-creds-path "$cbienv" "$targetDb")
CREDS=$(head -n -1 $credsPath | yq)
DBHOST=$(s cbi db get-hostname "$cbienv" "$targetDb")
DBTABLE=""
if [ "$targetDb" = "main" ]; then
	DBTABLE="cbi_data"
fi
echo "mysql://$(echo $CREDS | jq -r .USERNAME):$(echo $CREDS | jq -r .PASSWORD)@$DBHOST/$DBTABLE"
