#! /usr/bin/env bash
set -uo pipefail

for i in dev stg prd; do
    for j in main table; do
        echo "Checking db creds for $i $j"
        s cbi db auth regen-if-expired "$i" "$j"
    done
done

# s cbi db auth write-creds-to-mycnf
