#! /usr/bin/env bash
set -euo pipefail

cbienv=${1:-$(s cbi local curr-env-dwim)}
targetDb=${2:-"main"}

bwnotename="cbi-db-auth-creds-dir-$cbienv-$targetDb"

s bitwarden select-one "$bwnotename" | jq -r ".notes"
