#! /usr/bin/env bash
set -euo pipefail

cbienv=${1:-$(s cbi env-select-dwim)}
targetDb=${2:-"main"}
tmpfile=$(mktemp)
vault_targetDb=$targetDb
vault_targetDb_suffix=full
if [ $targetDb = "auth" ]; then
	vault_targetDb_suffix=read
fi
if [ $targetDb = "logo" ]; then
	vault_targetDb="logo-service"
fi
if [ $targetDb = "table" ]; then
	vault_targetDb="table-service"
fi
timeout 3 cbi vault -s "db_$vault_targetDb-$vault_targetDb_suffix" -e "$cbienv" | tee | rg ":" >$tmpfile
echo "New creds stored in $tmpfile"
NEW_CREDS=$(cat "$tmpfile")

if [[ $(echo "$NEW_CREDS" | rg ":" | wc -l) -lt 3 ]]; then
	echo "Failed to generate new db creds for $cbienv $targetDb"
	exit 1
fi

for i in $(seq 3); do echo; done
echo "Post generation stuff"
echo "$NEW_CREDS" | s cbi db auth store-creds "$cbienv" "$targetDb"
echo "$NEW_CREDS" | s cbi db auth write-creds-to-mycnf "$cbienv" "$targetDb"
echo "$NEW_CREDS" | s cbi db auth update-dbeaver-creds-via-stdin "$cbienv" "$targetDb"

for i in $(seq 3); do echo; done
echo "Registering refresh"
echo "s cbi db auth regen-creds $cbienv $targetDb" | at $(gdate -d "$(yq -r .EXPIRY <<<"$NEW_CREDS")")
