#! /usr/bin/env bash
set -euo pipefail

cbienv=${1:-$(s cbi env-select-dwim)}
targetDb=${2:-"main"}
tmpfile=$(mktemp)
vault_targetDb=$targetDb
if [ $targetDb = "logo" ]; then
	vault_targetDb="logo-service"
fi
if [ $targetDb = "table" ]; then
	vault_targetDb="table-service"
fi
cbi-vault -s "db_$vault_targetDb-full" -e "$cbienv" >$tmpfile
echo "New creds stored in $tmpfile"
NEW_CREDS=$(cat "$tmpfile")
if [[ $(echo "$NEW_CREDS" | rg ":" | wc -l) -lt 3 ]]; then
	echo "Failed to generate new db creds for $cbienv $targetDb"
	exit 1
fi
# TODO read EXPIRY field and run 'at' command to regenerate
echo "$NEW_CREDS" | rg ":" >"$(s cbi db auth creds-dir "$cbienv" "$targetDb")/$gdate +%s)"
