#! /usr/bin/env bash
set -euo pipefail

cbienv=${1:-$(s cbi env-select-dwim)}
targetDb=${2:-"main"}
tmpfile=$(mktemp)
vault_targetDb=$targetDb
if [ $targetDb = "logo" ]; then
	vault_targetDb="logo-service"
fi
if [ $targetDb = "table" ]; then
	vault_targetDb="table-service"
fi
cbi vault -s "db_$vault_targetDb-full" -e "$cbienv" | tee $tmpfile
echo "New creds stored in $tmpfile"
NEW_CREDS=$(cat "$tmpfile")

if [[ $(echo "$NEW_CREDS" | rg ":" | wc -l) -lt 3 ]]; then
	echo "Failed to generate new db creds for $cbienv $targetDb"
	exit 1
fi

echo "$NEW_CREDS" | s cbi db auth store-creds "$cbienv" "$targetDb"
echo "$NEW_CREDS" | s cbi db auth update-dbeaver-creds-via-stdin "$cbienv" "$targetDb"

# expect <<-EOF >/dev/null
# 	spawn mysql_config_editor set --skip-warn --login-path=$i-$j --user=$(s cbi db auth latest-creds-field USERNAME "$i" "$j") --host=$(s cbi db get-hostname "$i" "$j") --password
# 	expect "Enter password: "
# 	send "$(s cbi db auth latest-creds-field PASSWORD "$i" "$j")\r"
# 	expect eof
# EOF

# echo "s cbi db auth regen-creds $cbienv $targetDb" | at $(gdate -d "$(jq -r .EXPIRY <<<"$NEW_CREDS")")
