#! /usr/bin/env bash
set -euo pipefail

cbienv=$1
targetDb=$2

bwnotename="cbi-db-auth-creds-dir-$cbienv-$targetDb"

s bitwarden ensure-note-exists "$bwnotename"
s bitwarden update-note "$bwnotename" "$(rg ":")"
