#! /usr/bin/env bash
set -euo pipefail

cbienv=${1:-$(s cbi local curr-env-dwim)}
targetDb=${2:-"main"}

DBEAVERCONFIGBASE=""

if [[ $(uname) = "Linux" ]]; then
    DBEAVERCONFIGBASE="$HOME/.local/share/DBeaverData"
elif [[ $(uname) = "Darwin" ]]; then
    DBEAVERCONFIGBASE="$HOME/Library/DBeaverData"
else
    echo "Unsupported OS"
    exit 1
fi

DBEAVERCONNECTIONSFILE="$DBEAVERCONFIGBASE/workspace6/General/.dbeaver/data-sources.json"
# DBEAVERCONNECTIONSFILE="$DBEAVERCONFIGBASE/workspace6/General/.dbeaver/data-sources-cbi-$cbienv-$targetDb.json"

dbname="CBI $cbienv $targetDb"

if [[ ! -s $DBEAVERCONNECTIONSFILE ]]; then
    # jq --null-input --arg folder "CBI/$cbienv" --arg name "$dbname" --arg connname "mysql8-$(uuid)" '{ $connname: { name: $name, "read-only": false, "save-password": true, folder: $folder provider: "mysql",  driver: "mysql8", } }'
    # "mysql8-17827c7fcb2-142183083ce09f26": {
    #    "configuration": {
    #      "host": "mysql-dev.cbinsights.com",
    #      "port": "3306",
    #      "database": "cbi_data",
    #      "url": "jdbc:mysql://mysql-dev.cbinsights.com:3306/cbi_data",
    #      "type": "dev",
    #      "auth-model": "native",
    #      "user": "v-full-AJ93ARnU0",
    #      "password": "A1a-BE5UW00LkJ1zkPdo"
    #    }
    #  },

    echo "DBeaver config not setup at all yet, bailing"
    exit 1
fi

if ! cat "$DBEAVERCONNECTIONSFILE" | jq --arg dbname "$dbname" '.connections | to_entries | map(select(.value.name == $dbname)) | first' >/dev/null; then
    echo "DBeaver config does not have $cbienv $targetDb setup yet, bailing"
    exit 1
fi

credsInfo="$(cat /dev/stdin)"
conn_username="$(echo "$credsInfo" | jq -r .USERNAME)"
conn_password="$(echo "$credsInfo" | jq -r .PASSWORD)"
conn_host="$(s cbi db get-hostname "$cbienv" "$targetDb")"

cp "$DBEAVERCONNECTIONSFILE" "$DBEAVERCONNECTIONSFILE.bak-$(gdate +%s)"
TARGETCONNECTIONKEY=$(cat "$DBEAVERCONNECTIONSFILE" | jq --arg dbname "$dbname" '.connections | to_entries | map(select(.value.name == $dbname)) | first | .key' -r)
NEWDBEAVERCONNECTIONSFILE=$(cat "$DBEAVERCONNECTIONSFILE" | jq --arg targetConn "$TARGETCONNECTIONKEY" \
    '.connections[$targetConn].configuration.host = "'"$conn_host"'" |.connections[$targetConn].configuration.user = "'"$conn_username"'" | .connections[$targetConn].configuration.password = "'"$conn_password"'"')
if ! [ -z "$NEWDBEAVERCONNECTIONSFILE" ]; then
    echo "$NEWDBEAVERCONNECTIONSFILE" >"$DBEAVERCONNECTIONSFILE"
fi
