#! /usr/bin/env bash
set -euo pipefail

cbienv=${1:-$(s cbi local curr-env-dwim)}
targetDb=${2:-"main"}
credsInfo="$(cat /dev/stdin)"
conn_username="$(echo "$credsInfo" | rg USERNAME | yq -r .USERNAME)"
conn_password="$(echo "$credsInfo" | rg PASSWORD | yq -r .PASSWORD)"
conn_host="$(s cbi db get-hostname "$cbienv" "$targetDb")"

DBEAVERCONFIGBASE=""

if [[ $(uname) = "Linux" ]]; then
    DBEAVERCONFIGBASE="$HOME/.local/share/DBeaverData"
elif [[ $(uname) = "Darwin" ]]; then
    DBEAVERCONFIGBASE="$HOME/Library/DBeaverData"
else
    echo "Unsupported OS"
    exit 1
fi

DBEAVERCONNECTIONSFILE="$DBEAVERCONFIGBASE/workspace6/General/.dbeaver/data-sources.json"

if [[ ! -s $DBEAVERCONNECTIONSFILE ]]; then
    echo "DBeaver config not setup at all yet, bailing"
    exit 1
fi

jqUery=".connections | to_entries | map(select(.value.name == \"CBI $cbienv $targetDb\")) | first"
if ! cat "$DBEAVERCONNECTIONSFILE" | jq -e $jqUery; then
    echo "DBeaver config does not have $cbienv $targetDb setup yet, bailing"
    exit 1
fi
cp "$DBEAVERCONNECTIONSFILE" "$DBEAVERCONNECTIONSFILE.bak-$(gdate +%s)"
TARGETCONNECTIONKEY=$(cat "$DBEAVERCONNECTIONSFILE" | jq "$jqUery | first | .key" -r)
NEWDBEAVERCONNECTIONSFILE=$(cat "$DBEAVERCONNECTIONSFILE" | jq --arg targetConn "$TARGETCONNECTIONKEY" \
    '.connections[$targetConn].configuration.host = "'"$conn_host"'" |.connections[$targetConn].configuration.user = "'"$conn_username"'" | .connections[$targetConn].configuration.password = "'"$conn_password"'"')
if ! [ -z "$NEWDBEAVERCONNECTIONSFILE" ]; then
    echo "$NEWDBEAVERCONNECTIONSFILE" >"$DBEAVERCONNECTIONSFILE"
fi
