#! /usr/bin/env bash
set -euo pipefail

cbienv=${1:-$(s cbi local curr-env-dwim)}
targetDb=${2:-"main"}

DBEAVERCONFIGBASE=""

if [[ $(uname) = "Linux" ]]; then
    DBEAVERCONFIGBASE="$HOME/.local/share/DBeaverData"
elif [[ $(uname) = "Darwin" ]]; then
    DBEAVERCONFIGBASE="$HOME/Library/DBeaverData"
else
    echo "Unsupported OS"
    exit 1
fi

DBEAVERCONNECTIONSFILE="$DBEAVERCONFIGBASE/workspace6/General/.dbeaver/data-sources.json"

if [[ ! -s $DBEAVERCONNECTIONSFILE ]]; then
    echo "DBeaver config not setup at all yet, bailing"
    exit 1
fi

dbname="CBI $cbienv $targetDb"
if ! cat "$DBEAVERCONNECTIONSFILE" | jq --arg dbname "$dbname" '.connections | to_entries | map(select(.value.name == $dbname)) | first' > /dev/null; then
    echo "DBeaver config does not have $cbienv $targetDb setup yet, bailing"
    exit 1
fi

credsInfo="$(cat /dev/stdin)"
conn_username="$(echo "$credsInfo" | jq -r .USERNAME)"
conn_password="$(echo "$credsInfo" | jq -r .PASSWORD)"
conn_host="$(s cbi db get-hostname "$cbienv" "$targetDb")"

cp "$DBEAVERCONNECTIONSFILE" "$DBEAVERCONNECTIONSFILE.bak-$(gdate +%s)"
TARGETCONNECTIONKEY=$(cat "$DBEAVERCONNECTIONSFILE" | jq --arg dbname "$dbname" '.connections | to_entries | map(select(.value.name == $dbname)) | first | .key' -r)
NEWDBEAVERCONNECTIONSFILE=$(cat "$DBEAVERCONNECTIONSFILE" | jq --arg targetConn "$TARGETCONNECTIONKEY" \
    '.connections[$targetConn].configuration.host = "'"$conn_host"'" |.connections[$targetConn].configuration.user = "'"$conn_username"'" | .connections[$targetConn].configuration.password = "'"$conn_password"'"')
if ! [ -z "$NEWDBEAVERCONNECTIONSFILE" ]; then
    echo "$NEWDBEAVERCONNECTIONSFILE" >"$DBEAVERCONNECTIONSFILE"
fi
