#! /usr/bin/env bash
set -uo pipefail

if ! command -v mysql_config_editor; then
	echo "Skipping storing creds in my.cnf because mysql_config_editor is missing"
	exit 0
fi

i=$1 # env
j=$2 # table-name

expect <<-EOF >/dev/null
	spawn mysql_config_editor set --skip-warn --login-path=$i-$j --user=$(s cbi db auth latest-creds-field USERNAME "$i" "$j") --host=$(s cbi db get-hostname "$i" "$j") --password
	expect "Enter password: "
	send "$(s cbi db auth latest-creds-field PASSWORD "$i" "$j")\r"
	expect eof
EOF
