#! /usr/bin/env bash
set -uo pipefail

for i in dev stg prd; do
    for j in main table; do
        s cbi db auth latest-creds "$i" "$j" | s cbi db auth update-dbeaver-creds-via-stdin "$i" "$j"
    done
done
