#!/usr/bin/env bash
set -euo pipefail

endpoint=$1
shift

http --body https://3s1ehdl2012c9bryl8o5tydbsi9pfujz.ui.nabu.casa/api/$endpoint Authorization:"Bearer $(bw get item hass | jq '.fields[] | select(.name == "bearer-token").value' -r)" $*
