#!/usr/bin/env bash
set -euo pipefail
jobsWithArtifacts=$(s gitlab this-project-request jobs | jq 'map(select((.artifacts | length) > 0 and (.artifacts[].filename | index("artifacts.zip")))) | del(.[].commit.message)' -c)
jobInfo=$(echo "$jobsWithArtifacts" | tr '\r\n' ' ' | s fzf select-by-json-key "name")
# TODO somehow I need to only keep the most recent of each build name
# echo $jobsWithArtifacts | jq 'sort_by(.started_at) | last | .started_at'

targetJobName=$(echo "$jobInfo" | jq -r '.name' | sort -u | xargs)
currentbranch=$(urlencode $(git current-branch))
s gitlab this-project-request --download "jobs/artifacts/$currentbranch/download" "job==${targetJobName}"
mv --backup=t download.bin "artifacts-${targetJobName}.zip"
s util auto-decompress "artifacts-${targetJobName}.zip"
rm -f "artifacts-${targetJobName}.zip"
