#!/usr/bin/env bash
set -euo pipefail

jobsWithArtifacts=$(s gitlab artifacts jobs-with-artifacts-for-this-repo)
jobInfo=$(echo "$jobsWithArtifacts" | tr '\r\n' ' ' | s fzf select-by-json-key "name")
targetJobName=$(echo "$jobInfo" | jq -r '.name' | sort -u | xargs)
currentbranch=$(s util urlencode $(git current-branch))
s gitlab this-project-request --download "jobs/artifacts/$currentbranch/download" "job==${targetJobName}"
mv --backup=t download.bin "artifacts-${targetJobName}.zip"
s util auto-decompress "artifacts-${targetJobName}.zip"
rm -f "artifacts-${targetJobName}.zip"
