#!/usr/bin/env bash
set -euo pipefail

project=$1
job=$2

s gitlab project-request --download "$project" "jobs/$job/artifacts"
mv --backup=t download.bin "artifacts-${targetJobName}.zip"
s util auto-decompress "artifacts-${targetJobName}.zip"
rm -f "artifacts-${targetJobName}.zip"
