#!/usr/bin/env bash
set -euo pipefail

project=$1
job=$2

# preserve calling PWD for auth switching by directory
s gitlab project-request --download "$project" "jobs/$job/artifacts"
origdir=$PWD
cd $(mktemp -d)

mv -f $origdir/artifacts.bin ./artifacts-tmp-dl.zip
s util auto-decompress ./artifacts-tmp-dl.zip

zsh -l
