#!/usr/bin/env bash
set -euo pipefail

profileName="$1"
tgtProfileId=$(python -c 'print({"personal": "QW-EuxLBAUMUTLJvgHd7C", "cbi":"h3jJMwMHUSWsBCZqHmCgV"}["'"$profileName"'"])')
cookieSite="${2:-"$(s chrome history-urls | s util strip-protocol | s util extract-base-domain | sort -u | fzf)"}"
port=$(jq '.'"$tgtProfileId" ~/.cookie-monger-profile-port-map)
http ":$port/cookies" domain=="$cookieSite" --body
