#!/usr/bin/env bash
set -euo pipefail

cookieSite="${1:-"$(s chrome history-urls | s util strip-protocol | s util extract-base-domain | sort -u | fzf)"}"
tmpDir=$(mktemp -d)
set +e
for el in $(jq "to_entries | .[]" -c ~/.cookie-monger-profile-port-map); do
    profileid=$(jq ".key" -r <<<"$el")
    port=$(jq ".value" -r <<<"$el")
    http ":$port/cookies" domain=="$cookieSite" --body >"$tmpDir/$profileid"
done
set -e
s util yq-merge-all-arrays $tmpDir/*
