#!/usr/bin/env bash

set -euo pipefail

tgt_file="$(s which "$@" | xargs realpath)"

cd $(dirname "$tgt_file")

if (for scriptdir in $(echo "$SCRIPTS_PATH" | tr ':' '\n'); do fd -t x . "$scriptdir"; done | rg "s $*"); then
    s Yn "This script appears to be referenced in some other scripts! Continue?"
fi

# git stash --all

git rm -f "$tgt_file"

# Try deleting all related files that may exist or not
git rm --ignore-unmatch -f "$tgt_file.help"
git rm --ignore-unmatch -f "$tgt_file.inproc"

git commit -m "deleted script"

# git stash pop
