#!/usr/bin/env bash

set -euo pipefail

argument=${@:-"$(s meta last-invoked "(edit|cat|whicha?)")"}

tgt_file="$(s which "$argument")"
# TODO test if this is a chezmoi managed source path, if so edit via chezmoi edit --apply

$EDITOR "$tgt_file"
