#!/usr/bin/env bash

set -euo pipefail

argument=${@:-"$(s meta last-invoked "(edit|cat|whicha?)")"}

tgt_file="$(s which "$argument")"

if cat ~/.local/chezmoi-managed-paths | grep -q '^'"$tgt_file"; then
    chezmoi edit --apply "$tgt_file"
else
    $EDITOR "$tgt_file"
fi
