#!/usr/bin/env bash
set -euo pipefail

# export S_INNER_CALL=1

if [[ -z ${@:-""} ]]; then
  argument="$(s meta last-invoked "(edit|cat|whicha?)")"
else
  argument="$@"
fi

file="$(s which "$argument")"

helpfile="$file.help"
if [[ -d "$file" ]]; then
  # s will print subcommands when given a directory
  s "$@"
elif [[ -f "$helpfile" ]]; then
  cat "$helpfile"
else
  help=$(sed -nE -e '/^#!/d' -e '/^#/{s/^# *//; p; q;}' "$file")
  if [[ -z "$help" ]]; then
    echo "there is no help for you here" >&2
    exit 1
  else
    echo "$help"
  fi
fi
