#!/usr/bin/env bash

set -uo pipefail

tgt_file_cmpts=""
dest_file_cmpts=""
while [[ $# -gt 0 ]]; do
    case "$1" in
        --)
            shift
            dest_file_cmpts=$(echo "$*" | xargs) # xargs to trim whitespace
            tgt_file_cmpts=$(echo "$tgt_file_cmpts" | xargs)
            break
            ;;
        *)
            tgt_file_cmpts="$tgt_file_cmpts$1 "
            ;;
    esac
    shift
done

tgt_file="$(s which "$tgt_file_cmpts" | xargs realpath)"

if [[ -z $dest_file_cmpts ]]; then
    echo "Enter destination for link:\n"
    read dest_file_cmpts
fi

dest_file="$(s which "$dest_file_cmpts" | xargs realpath)"

dest_dir=$(dirname "$dest_file")
mkdir -p "$dest_dir"

scriptgit() {
    git -C "$dest_dir" "$@"
}

ln -s "$tgt_file" "$dest_file"
scriptgit add "$dest_file"
scriptgit commit -m "linked script $tgt_file_cmpts -> $dest_file_cmpts"
