#!/usr/bin/env bash

set -uo pipefail

src_file_cmpts=""
link_file_cmpts=""
while [[ $# -gt 0 ]]; do
    case "$1" in
        --)
            shift
            link_file_cmpts=$(echo "$*" | xargs) # xargs to trim whitespace
            src_file_cmpts=$(echo "$src_file_cmpts" | xargs)
            break
            ;;
        *)
            src_file_cmpts="$src_file_cmpts$1 "
            ;;
    esac
    shift
done

src_file="$(s which "$src_file_cmpts" | xargs realpath)"

if [[ -z $link_file_cmpts ]]; then
    echo "Enter destination for link:\n"
    read link_file_cmpts
fi


dest_file="$HOME/.local/chez-managed-s-scripts/$(echo "$link_file_cmpts" | tr ' ' '/')"
echo "Dest file is $dest_file"
dest_dir=$(dirname "$dest_file")
mkdir -p "$dest_dir"

ln -s "$src_file" "$dest_file"

chezmoi add --template-symlinks "$dest_file"
chezmoi git add .
# chezmoi git commit -- -m "linked script $src_file_cmpts -> $link_file_cmpts"
