#!/usr/bin/env bash
set -euo pipefail

script_name="$1"

script_path=$(s which "$script_name")

echo "Enter help info"
read -r helpinfo

echo "$helpinfo" >> "$script_path.help"

git -C "$(realpath "$script_path")" add "*.help"
