#!/usr/bin/env bash
set -euo pipefail

cmd=""
script_name=""

while test $# -gt 0; do
  case "$1" in
  --)
    shift
    cmd="$*"
    break
    ;;
  *)
    script_name="$script_name$1 "
    ;;
  esac
  shift
done

script_name=$(echo "$script_name" | sd '\s*$' '')

script_name="$(echo "$script_name")"
script_path="$(s which $script_name)"

if [ -f "$script_path" ]; then
  echo "File already exists!"
  exit 1
fi

mkdir -p "$(dirname "$script_path")"
script_path="$(realpath "$script_path")"
echo >&2 "Script name is: $script_name"
echo >&2 "Script path is: $script_path"

# dest_dir=$(dirname "$script_path")
# scriptgit() {
#     git -C "$dest_dir" "$@"
# }

# scriptgit switch master

# scriptgit stash --all

s touch "$script_path"
cat >"$script_path" <<EOF
#!/usr/bin/env bash
set -euo pipefail

EOF

chmod +x "$script_path"
if [[ -z "$cmd" ]]; then
  s edit "$script_name"
else
  echo "$cmd" >>"$script_path"
  echo >>"$script_path"
fi

# s mkhelp "$script_name"

# scriptgit add "$script_path*"
# scriptgit commit --message 'added new s script'
#
# scriptgit stash pop
