#!/usr/bin/env bash

set -uo pipefail

tgt_file_cmpts=""
dest_file_cmpts=""
while [[ $# -gt 0 ]]; do
    case "$1" in
        --)
            shift
            dest_file_cmpts=$(echo "$*" | xargs) # xargs to trim whitespace
            tgt_file_cmpts=$(echo "$tgt_file_cmpts" | xargs)
            break
            ;;
        *)
            tgt_file_cmpts="$tgt_file_cmpts$1 "
            ;;
    esac
    shift
done

tgt_file="$(s which "$tgt_file_cmpts" | xargs realpath)"

if [[ -z $dest_file_cmpts ]]; then
    echo "Enter destination for script:\n"
    read dest_file_cmpts
fi

dest_file="$(s which "$dest_file_cmpts" | xargs realpath)"

dest_dir=$(dirname "$dest_file")
tgt_dir=$(dirname "$tgt_file")
mkdir -p "$dest_dir"

isWithinRepoMove=0
if [[ $(git -C $tgt_dir remote get-url origin) = $(git -C $dest_dir remote get-url origin) ]]; then
    isWithinRepoMove=1
fi

scriptgit() {
    if [[ $isWithinRepoMove -eq 1 ]]; then
        git -C "$dest_dir" "$@"
    else
        git -C "$dest_dir" "$@"
        git -C "$tgt_dir" "$@"
    fi
}

scriptmv() {
    if [[ $isWithinRepoMove -eq 1 ]]; then
        scriptgit mv $*
    else
        mv $*
    fi
}

# scriptgit stash --all

scriptmv "$tgt_file" "$dest_file"

if [ -e "$tgt_file.help" ]; then
    scriptmv "$tgt_file.help" "$dest_file.help"
fi

if [ -e "$tgt_file.inproc" ]; then
    scriptmv "$tgt_file.inproc" "$dest_file.inproc"
fi

ln -s "$dest_file" "$tgt_file"
touch "$tgt_file.linger"
scriptgit add "$tgt_file" "$tgt_file.linger"

(
    fd -t f . ~/.local/share/chezmoi
    for scriptdir in $(echo "$SCRIPTS_PATH" | tr ':' $'\n'); do
        fd -t x . "$scriptdir"
    done
) | sad --exact "s $tgt_file_cmpts" "s $dest_file_cmpts"

scriptgit commit -m "renamed script $tgt_file_cmpts -> $dest_file_cmpts"

# scriptgit stash pop
