#!/usr/bin/env bash

set -uo pipefail

tgt_file_cmpts=""
dest_file_cmpts=""
while [[ $# -gt 0 ]]; do
    case "$1" in
        --)
            shift
            dest_file_cmpts=$(echo "$*" | xargs) # xargs to trim whitespace
            tgt_file_cmpts=$(echo "$tgt_file_cmpts" | xargs)
            break
            ;;
        *)
            tgt_file_cmpts="$tgt_file_cmpts$1 "
            ;;
    esac
    shift
done

tgt_file="$(s which "$tgt_file_cmpts" | xargs realpath)"

if [[ -z $dest_file_cmpts ]]; then
    echo "Enter destination for script:\n"
    read dest_file_cmpts
fi

dest_file="$(s which "$dest_file_cmpts" | xargs realpath)"

dest_dir=$(dirname "$dest_file")
mkdir -p "$dest_dir"

scriptgit() {
    git -C "$dest_dir" "$@"
}

scriptgit stash --all

scriptgit mv "$tgt_file" "$dest_file" || mv "$tgt_file" "$dest_file"

if [ -e "$tgt_file.help" ]; then
    scriptgit mv "$tgt_file.help" "$dest_file.help" || mv "$tgt_file.help" "$dest_file.help"
fi

if [ -e "$tgt_file.inproc" ]; then
    scriptgit mv "$tgt_file.inproc" "$dest_file.inproc" || mv "$tgt_file.inproc" "$dest_file.inproc"
fi

for scriptdir in $(echo "$SCRIPTS_PATH" | tr ':' $'\n'); do
    fd -t x . "$scriptdir"
done | sad --exact "s $*" "s $dest_file_cmpts"

scriptgit commit -m "renamed script $tgt_file_cmpts -> $dest_file_cmpts"

scriptgit stash pop
