#!/usr/bin/env bash
set -euo pipefail

target_cal="${1:-j79}"

todayd=$(date +%F)
tomorrowd=$(date +%F -d "$todayd + 1 day")

gcalcli --config-folder ~/.local/gcalcli/$target_cal agenda --nodeclined --nostarted --tsv $todayd $tomorrowd
