#!/usr/bin/env bash
set -euo pipefail

target_cal="$1"
shift

todayd=$(date +%F)
tomorrowd=$(date +%F -d "$todayd + 1 day")

s calendar helper $target_cal agenda $todayd $tomorrowd --nodeclined --nostarted --tsv $*
