#! /usr/bin/env bash
set -euo pipefail

cbienv=${1:-$(s cbi local curr-env-dwim)}
targetDb=${2:-"main"}

mycli --login-path "$cbienv-$targetDb" --csv -e "
		SELECT c.company, c.id_cbi_entity
		FROM cbi_data.company c
		WHERE
			c.company LIKE '$1%'
		" | s util convert-csv-to-json | s fzf select-by-json-key "company" | jq -r '.id_cbi_entity'
