#!/usr/bin/env bash
set -euo pipefail

cd ~/.config/nix/home-manager
nix flake update
chezmoi add --create flake.lock
trap "git -C ~/.local/share/chezmoi/ checkout -- private_dot_config/nix/home-manager/create_flake.lock; rm -f ~/.config/nix/home-manager/flake.lock; chezmoi apply --force ~/.config/nix/home-manager/flake.lock; exit 1" ERR

cd

s dot run-script home_manager_update

if [[ ${CHEZ_JM_EMACS_ENABLED:-""} == 1 ]]; then
	s emacs reload-config-lite
	s emacs test integration
fi

cd ~/.local/share/chezmoi/private_dot_config/nix/home-manager
git add *flake*
git commit -m "flake update" && {
	git pull --no-edit
	git push --recurse-submodules=on-demand
}
