#!/usr/bin/env bash
set -euo pipefail
tgt_file=${1:-"$(git root-directory)/.env.gitlab-mirror"}

existing_variables=$(s gitlab this-project-request "variables" | jq -r '.[].key')
bat "$tgt_file" | while IFS= read -r; do
	key=$(echo "$REPLY" | cut -d= -f1 || echo "")
	if [[ -z "$key" ]]; then
		continue
	fi
	if echo "$existing_variables" | rg -q "$key"; then
		s gitlab this-project-request PUT "variables/$key" value=$(eval echo '$'"$key")
	else
		s gitlab this-project-request POST variables key=$key value=$(eval echo '$'"$key") masked=true || s gitlab this-project-request POST variables key=$key value=$(eval echo '$'"$key")
	fi
	echo
done
