#!/usr/bin/env bash
set -euo pipefail

unsyncedDevices=$(s syncthing devices-missing-bytes)
if [[ -n "$unsyncedDevices" ]]; then
    echo "WARN: syncthing devices not fully synced"
    echo "$unsyncedDevices"
fi
