#!/usr/bin/env bash
set -euo pipefail

vpsname="$1"

TAILAUTH=$(bw get item tailscale | jq '.fields[] | select(.name == "api-key").value' -r)
https --auth "$TAILAUTH:" \
    "api.tailscale.com/api/v2/tailnet/jackmac79@gmail.com/devices" |
    jq --arg tgt "$vpsname" '.devices[] | select(.hostname == $tgt) | .id' -r |
    xargs --no-run-if-empty -I% https --body --auth "$TAILAUTH:" DELETE "api.tailscale.com/api/v2/device/%"
