#!/usr/bin/env bash
set -euo pipefail

choice=$(s tailscale pick-ip "${1:-""}")
shift

if [ -z $choice ]; then
    echo "fuck am i supposed to do then, pick a real host"
    exit 1
fi

ssh "$choice" $*
