#!/usr/bin/env bash
set -euo pipefail

currenv=$(s cbi env-select-dwim)
currbranch=$(git rev-parse --abbrev-ref HEAD)

XNOMAD_ADDR=""

if [[ $currenv = "dev" ]]; then
  if [[ $currbranch = "staging" ]]; then
    echo "Warning branch env mismatch! Maybe you want to connect to staging?" >> /dev/stderr
  fi
  XNOMAD_ADDR=$NOMAD_ADDR_DEV
fi

if [[ $currenv = "stg" ]]; then
  if [[ $currbranch = "develop" ]]; then
    echo "Warning branch env mismatch! Maybe you want to connect to develop?" >> /dev/stderr
  fi
  XNOMAD_ADDR=$NOMAD_ADDR_STG
fi

NOMAD_ADDR=$XNOMAD_ADDR nomad $*
