#!/usr/bin/env bash
set -euo pipefail

jiraticket=$(s jira select-active-ticket-dwim "${1:-""}")
REGISTRY_FILE="$HOME/cbinsights/ticket-repo-registry.json"

# ensure branchname has been setup
s cbi get-branchname-dwim "$jiraticket" > /dev/null

# NOTE this should be a string JSON array
knownRepos=$(cat "$REGISTRY_FILE" | jq -r --arg ticket $jiraticket '.[$ticket] | select(. != null)')

if [[ -z "$knownRepos" ]]; then
    reposForTicket=$(s cbi svc select-many | jo -a | jq -c)
    cat "$REGISTRY_FILE" | jq --arg ticket $jiraticket --argjson repolist "$reposForTicket" '.[($ticket)] = $repolist' | sponge "$REGISTRY_FILE"
else
    reposForTicket=$(echo "$knownRepos" | jq -c)
fi

echo "Starting services"
echo "$reposForTicket" | jq -r '.[]' | tee | xargs -n1 s cbi start-service
